package protocodex

// resourceAPIMappings and serverHandlerMappings are reviewed Go-owned inputs
// copied from appendix-current-protocol-inventory.md. Rust manifest/schema files
// remain the protocol source of truth; these rows own Go public API decisions.
const stage5cSafeIntegrationReason = "live app-server coverage exercises command, process, config, and filesystem safe paths; remaining stateful variants retain package tests"
const stage5dSafeIntegrationReason = "live app-server coverage exercises safe app, MCP status, plugin, and skill listing; remaining methods require external services or mutate persisted plugin state"
const stage5eSafeIntegrationReason = "live app-server coverage exercises safe model, remote-control, review, and account-read paths; remaining methods require external state unavailable in the hermetic fixture"
const stage5eAuthSafeIntegrationReason = "a dedicated debug-only app-server fixture exercises production account login and backend paths without release authentication hooks; logout, cancel, and email endpoints retain package tests because they mutate account state"
const stage5eRemoteSafeIntegrationReason = "paired remote-control service or session is unavailable in the hermetic app-server fixture; package tests cover the external-session variants"
const stage5fSafeIntegrationReason = "live app-server coverage exercises the safe Linux resource paths; remaining methods require optional services or mutate persisted state and retain package tests"
const stage5fFeedbackSafeIntegrationReason = "feedback upload is side-effecting and auth-bound, so mocked package tests cover it without sending external feedback"
const stage5fWindowsSafeIntegrationReason = "Windows sandbox is Windows-runtime-bound; current Stage 5F has package tests for unsupported runtimes and mocked Windows-runtime JSON-RPC only"
const marketplaceSafeIntegrationReason = "the manifest exposes only side-effecting marketplace add, remove, and upgrade methods; Linux release tests do not mutate marketplace configuration"
const lifecycleSafeIntegrationReason = "real app-server tests exercise thread/start, thread/list, and turn/start; remaining thread and turn methods mutate lifecycle state or require pre-existing session data, so package tests own those variants"
const mcpOAuthSafeIntegrationReason = "MCP OAuth requires an external authorization provider and browser callback; package tests cover the handle lifecycle without initiating external authentication"
const realtimeSafeIntegrationReason = "realtime methods require an external websocket and audio backend; package tests cover routing, handles, and terminal lifecycle without opening a release-time realtime session"
const skillsMutationSafeIntegrationReason = "skills extra-root and config-write methods mutate persisted SDK configuration; package tests cover them without changing release-runner configuration"

var serverNotificationResourceMappings = []ServerNotificationResourceMapping{
	{
		Method:         "account/updated",
		ResourceOwners: []string{"Accounts"},
		ReviewNote:     "global account state notification consumed by account wrappers",
	},
	{
		Method:         "account/rateLimits/updated",
		ResourceOwners: []string{"Accounts"},
		ReviewNote:     "global account rate-limit notification consumed by account wrappers",
	},
	{
		Method:         "app/list/updated",
		ResourceOwners: []string{"Apps"},
		ReviewNote:     "global app-list notification consumed by app list wrappers",
	},
	{
		Method:         "configWarning",
		ResourceOwners: []string{"Config"},
		ReviewNote:     "global config warning notification consumed by config wrappers and diagnostics",
	},
	{
		Method:         "deprecationNotice",
		ResourceOwners: []string{"Threads"},
		ReviewNote:     "global deprecation notice consumed by thread-facing user notification flows",
	},
	{
		Method:         "error",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume turn-scoped error notifications while waiting for review completion",
	},
	{
		Method:         "guardianWarning",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume guardian warning notifications emitted during review turns",
	},
	{
		Method:         "item/agentMessage/delta",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume agent-message deltas from the review turn lifecycle",
	},
	{
		Method:         "item/commandExecution/outputDelta",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume command execution output deltas produced by review turns",
	},
	{
		Method:         "item/commandExecution/terminalInteraction",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume terminal interaction events produced by review turns",
	},
	{
		Method:         "item/completed",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume item completion notifications from review turn results",
	},
	{
		Method:         "item/fileChange/outputDelta",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume file-change output deltas produced by review turns",
	},
	{
		Method:         "item/fileChange/patchUpdated",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume patch update events produced by review turns",
	},
	{
		Method:         "item/mcpToolCall/progress",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume MCP progress items produced by review turns",
	},
	{
		Method:         "item/plan/delta",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume plan deltas produced by review turns",
	},
	{
		Method:         "item/reasoning/summaryPartAdded",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume reasoning summary part events produced by review turns",
	},
	{
		Method:         "item/reasoning/summaryTextDelta",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume reasoning summary text deltas produced by review turns",
	},
	{
		Method:         "item/reasoning/textDelta",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume reasoning text deltas produced by review turns",
	},
	{
		Method:         "item/started",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume item start notifications from review turn lifecycle",
	},
	{
		Method:         "rawResponseItem/completed",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume raw response completion notifications from review turn lifecycle",
	},
	{
		Method:         "serverRequest/resolved",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume server request resolution notifications during review turns",
	},
	{
		Method:         "skills/changed",
		ResourceOwners: []string{"Skills"},
		ReviewNote:     "global skill inventory notification consumed by skills wrappers",
	},
	{
		Method:         "thread/realtime/closed",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume thread realtime closed lifecycle notifications",
	},
	{
		Method:         "thread/realtime/error",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume thread realtime error lifecycle notifications",
	},
	{
		Method:         "thread/realtime/itemAdded",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume item-added events for streaming session state",
	},
	{
		Method:         "thread/realtime/outputAudio/delta",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume output audio deltas for streaming audio",
	},
	{
		Method:         "thread/realtime/sdp",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume SDP negotiation notifications",
	},
	{
		Method:         "thread/realtime/started",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume thread realtime started lifecycle notifications",
	},
	{
		Method:         "thread/realtime/transcript/delta",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume transcript deltas for streaming text",
	},
	{
		Method:         "thread/realtime/transcript/done",
		ResourceOwners: []string{"Realtime"},
		ReviewNote:     "realtime sessions consume transcript completion notifications",
	},
	{
		Method:         "turn/completed",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume review turn completion as the primary review lifecycle result",
	},
	{
		Method:         "turn/diff/updated",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume diff updates emitted by review turns",
	},
	{
		Method:         "turn/moderationMetadata",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume moderation metadata emitted by review turns",
	},
	{
		Method:         "turn/plan/updated",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume plan updates emitted by review turns",
	},
	{
		Method:         "turn/started",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume review turn start lifecycle notifications",
	},
	{
		Method:         "warning",
		ResourceOwners: []string{"Reviews"},
		ReviewNote:     "review handles consume warning notifications emitted during review turns",
	},
	{
		Method:         "windows/worldWritableWarning",
		ResourceOwners: []string{"WindowsSandbox"},
		ReviewNote:     "global Windows writable-directory warning consumed by Windows sandbox diagnostics",
	},
	{
		Method:         "windowsSandbox/setupCompleted",
		ResourceOwners: []string{"WindowsSandbox"},
		ReviewNote:     "global Windows sandbox setup notification consumed by sandbox wrappers",
	},
}

var resourceAPIMappings = []ResourceAPIMapping{
	{
		Method:                "account/login/start",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.StartChatGPTLogin / Accounts.StartDeviceCodeLogin / Accounts.LoginWithAPIKey / Accounts.LoginWithAmazonBedrock / LoginHandle",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "login, err := client.Accounts.StartDeviceCodeLogin(ctx); login, err = client.Accounts.StartChatGPTLogin(ctx); err = client.Accounts.LoginWithAPIKey(ctx, codex.APIKey(\"test-key\")); err = client.Accounts.LoginWithAmazonBedrock(ctx, codex.APIKey(\"test-key\"), \"eu-central-1\"); result, err := login.Wait(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationOwner:  "integration_auth_test.go",
		DocsExampleOwner:      "examples/login_account",
		ReviewNote:            "typed handle workflow plus API-key and Amazon Bedrock helpers with redacted secret handling; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "account/login/cancel",
		ResourceOwner:         "Accounts",
		WrapperName:           "LoginHandle.Cancel",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "login.Cancel(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationReason: stage5eAuthSafeIntegrationReason,
		DocsExampleOwner:      "examples/login_account",
		ReviewNote:            "typed handle workflow",
	},
	{
		Method:                "account/logout",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.Logout",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Accounts.Logout(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationReason: stage5eAuthSafeIntegrationReason,
		DocsExampleOwner:      "examples/login_account",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "account/rateLimits/read",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.RateLimits",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Accounts.RateLimits(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationOwner:  "integration_auth_test.go",
		DocsExampleOwner:      "examples/login_account",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "account/rateLimitResetCredit/consume",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.ConsumeRateLimitResetCredit",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Accounts.ConsumeRateLimitResetCredit(ctx, protocol.ConsumeAccountRateLimitResetCreditParams{IDempotencyKey: \"reset-credit-idempotency-key\"})",
		UnitTestOwner:         "accounts_test.go",
		SafeIntegrationOwner:  "integration_auth_test.go",
		DocsExampleOwner:      "README accounts",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "account/usage/read",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.Usage",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Accounts.Usage(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationOwner:  "integration_auth_test.go",
		DocsExampleOwner:      "examples/login_account",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "account/workspaceMessages/read",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.ReadWorkspaceMessages",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Accounts.ReadWorkspaceMessages(ctx)",
		UnitTestOwner:         "accounts_test.go",
		SafeIntegrationReason: stage5eAuthSafeIntegrationReason,
		DocsExampleOwner:      "README accounts",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "account/sendAddCreditsNudgeEmail",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.SendAddCreditsNudgeEmail",
		WrapperFile:           "accounts.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Accounts.SendAddCreditsNudgeEmail(ctx, protocol.SendAddCreditsNudgeEmailParams{CreditType: protocol.AddCreditsNudgeCreditTypeCredits})",
		UnitTestOwner:         "accounts_test.go",
		SafeIntegrationReason: stage5eAuthSafeIntegrationReason,
		DocsExampleOwner:      "README accounts",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "account/read",
		ResourceOwner:         "Accounts",
		WrapperName:           "Accounts.Read",
		WrapperFile:           "accounts.go",
		PublicSignature:       "Read(ctx context.Context, refreshToken bool)",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Accounts.Read(ctx, false)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationOwner:  "integration_auth_test.go",
		DocsExampleOwner:      "examples/login_account",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "app/list",
		ResourceOwner:         "Apps",
		WrapperName:           "Apps.List",
		WrapperFile:           "apps.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Apps.List(ctx, protocol.AppsListParams{})",
		UnitTestOwner:         "apps_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "command/exec",
		ResourceOwner:         "Commands",
		WrapperName:           "Commands.Exec",
		WrapperFile:           "commands.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "cmd, err := client.Commands.Exec(ctx, codex.CommandExecOptions{Command: []string{\"echo\", \"ok\"}}); stream, err := cmd.Stream(ctx); result, err := cmd.Wait(ctx)",
		UnitTestOwner:         "commands_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; SDK generates/injects process identity; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "command/exec/write",
		ResourceOwner:         "Commands",
		WrapperName:           "CommandHandle.Write / CloseStdin",
		WrapperFile:           "commands.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "cmd.Write(ctx, []byte(\"input\")); cmd.CloseStdin(ctx)",
		UnitTestOwner:         "commands_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects process identity",
	},
	{
		Method:                "command/exec/terminate",
		ResourceOwner:         "Commands",
		WrapperName:           "CommandHandle.Terminate",
		WrapperFile:           "commands.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "cmd.Terminate(ctx)",
		UnitTestOwner:         "commands_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects process identity",
	},
	{
		Method:                "command/exec/resize",
		ResourceOwner:         "Commands",
		WrapperName:           "CommandHandle.Resize",
		WrapperFile:           "commands.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "cmd.Resize(ctx, codex.TerminalSize{Rows: 24, Cols: 80})",
		UnitTestOwner:         "commands_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects process identity",
	},
	{
		Method:                "config/mcpServer/reload",
		ResourceOwner:         "Config",
		WrapperName:           "Config.ReloadMCPServers",
		WrapperFile:           "config_resource.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Config.ReloadMCPServers(ctx)",
		UnitTestOwner:         "config_resource_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "config/read",
		ResourceOwner:         "Config",
		WrapperName:           "Config.Read",
		WrapperFile:           "config_resource.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Config.Read(ctx, protocol.ConfigReadParams{})",
		UnitTestOwner:         "config_resource_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "config/value/write",
		ResourceOwner:         "Config",
		WrapperName:           "Config.WriteValue",
		WrapperFile:           "config_resource.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Config.WriteValue(ctx, protocol.ConfigValueWriteParams{})",
		UnitTestOwner:         "config_resource_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "config/batchWrite",
		ResourceOwner:         "Config",
		WrapperName:           "Config.BatchWrite",
		WrapperFile:           "config_resource.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Config.BatchWrite(ctx, protocol.ConfigBatchWriteParams{})",
		UnitTestOwner:         "config_resource_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "configRequirements/read",
		ResourceOwner:         "Config",
		WrapperName:           "Config.ReadRequirements",
		WrapperFile:           "config_resource.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Config.ReadRequirements(ctx)",
		UnitTestOwner:         "config_resource_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "README config",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "experimentalFeature/list",
		ResourceOwner:         "ExperimentalFeatures",
		WrapperName:           "ExperimentalFeatures.List",
		WrapperFile:           "experimental_features.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.ExperimentalFeatures.List(ctx, protocol.ExperimentalFeatureListParams{ThreadID: protocol.Some(\"thread-1\")})",
		UnitTestOwner:         "experimental_features_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "experimentalFeature/enablement/set",
		ResourceOwner:         "ExperimentalFeatures",
		WrapperName:           "ExperimentalFeatures.SetEnablement",
		WrapperFile:           "experimental_features.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.ExperimentalFeatures.SetEnablement(ctx, protocol.ExperimentalFeatureEnablementSetParams{Enablement: map[string]bool{\"feature\": true}})",
		UnitTestOwner:         "experimental_features_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "externalAgentConfig/detect",
		ResourceOwner:         "ExternalAgents",
		WrapperName:           "ExternalAgents.DetectConfig",
		WrapperFile:           "external_agents.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.ExternalAgents.DetectConfig(ctx, protocol.ExternalAgentConfigDetectParams{Cwds: protocol.Some([]string{\"/repo\"}), IncludeHome: protocol.SomeNonNull(true)})",
		UnitTestOwner:         "external_agents_test.go",
		SafeIntegrationReason: stage5eSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "externalAgentConfig/import",
		ResourceOwner:         "ExternalAgents",
		WrapperName:           "ExternalAgents.ImportConfig",
		WrapperFile:           "external_agents.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.ExternalAgents.ImportConfig(ctx, protocol.ExternalAgentConfigImportParams{MigrationItems: []protocol.ExternalAgentConfigMigrationItem{}, Source: protocol.Some(\"codex\")})",
		UnitTestOwner:         "external_agents_test.go",
		SafeIntegrationReason: stage5eSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "externalAgentConfig/import/readHistories",
		ResourceOwner:         "ExternalAgents",
		WrapperName:           "ExternalAgents.ReadImportHistories",
		WrapperFile:           "external_agents.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.ExternalAgents.ReadImportHistories(ctx)",
		UnitTestOwner:         "external_agents_test.go",
		SafeIntegrationReason: stage5eSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "feedback/upload",
		ResourceOwner:         "Feedback",
		WrapperName:           "Feedback.Upload",
		WrapperFile:           "feedback.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Feedback.Upload(ctx, protocol.FeedbackUploadParams{Classification: \"bug\", ThreadID: protocol.Some(\"thread-1\")})",
		UnitTestOwner:         "feedback_test.go",
		SafeIntegrationReason: stage5fFeedbackSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper; upload uses generated neverRetryAfterWrite metadata",
	},
	{
		Method:                "fs/readFile",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.ReadFile",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FileSystem.ReadFile(ctx, protocol.FsReadFileParams{})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "fs/writeFile",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.WriteFile",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FileSystem.WriteFile(ctx, protocol.FsWriteFileParams{})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "fs/createDirectory",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.CreateDirectory",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FileSystem.CreateDirectory(ctx, protocol.FsCreateDirectoryParams{})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "fs/getMetadata",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.GetMetadata",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FileSystem.GetMetadata(ctx, protocol.FsGetMetadataParams{})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "fs/readDirectory",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.ReadDirectory",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FileSystem.ReadDirectory(ctx, protocol.FsReadDirectoryParams{})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "fs/remove",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.Remove",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FileSystem.Remove(ctx, protocol.FsRemoveParams{})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "fs/copy",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.Copy",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FileSystem.Copy(ctx, protocol.FsCopyParams{})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "fs/watch",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystem.Watch",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "watch, start, err := client.FileSystem.Watch(ctx, codex.FileSystemWatchOptions{Path: \"/repo\"})",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; SDK generates/injects watch identity; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "fs/unwatch",
		ResourceOwner:         "FileSystem",
		WrapperName:           "FileSystemWatchHandle.Close",
		WrapperFile:           "filesystem.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "watch.Close(ctx)",
		UnitTestOwner:         "filesystem_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow",
	},
	{
		Method:                "fuzzyFileSearch",
		ResourceOwner:         "FuzzyFileSearch",
		WrapperName:           "FuzzyFileSearch.Search",
		WrapperFile:           "fuzzy_file_search.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.FuzzyFileSearch.Search(ctx, protocol.FuzzyFileSearchParams{Query: \"main.go\", Roots: []string{\"/repo\"}})",
		UnitTestOwner:         "fuzzy_file_search_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "hooks/list",
		ResourceOwner:         "Hooks",
		WrapperName:           "Hooks.List",
		WrapperFile:           "hooks.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Hooks.List(ctx, protocol.HooksListParams{})",
		UnitTestOwner:         "hooks_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/skills_hooks",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "marketplace/add",
		ResourceOwner:         "Marketplace",
		WrapperName:           "Marketplace.Add",
		WrapperFile:           "marketplace.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Marketplace.Add(ctx, protocol.MarketplaceAddParams{Source: \"https://example.test/marketplace.git\"})",
		UnitTestOwner:         "marketplace_test.go",
		SafeIntegrationReason: marketplaceSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "marketplace/remove",
		ResourceOwner:         "Marketplace",
		WrapperName:           "Marketplace.Remove",
		WrapperFile:           "marketplace.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Marketplace.Remove(ctx, protocol.MarketplaceRemoveParams{MarketplaceName: \"default\"})",
		UnitTestOwner:         "marketplace_test.go",
		SafeIntegrationReason: marketplaceSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "marketplace/upgrade",
		ResourceOwner:         "Marketplace",
		WrapperName:           "Marketplace.Upgrade",
		WrapperFile:           "marketplace.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Marketplace.Upgrade(ctx, protocol.MarketplaceUpgradeParams{})",
		UnitTestOwner:         "marketplace_test.go",
		SafeIntegrationReason: marketplaceSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "mcpServer/oauth/login",
		ResourceOwner:         "MCP",
		WrapperName:           "MCP.OAuthLogin / MCPOAuthHandle",
		WrapperFile:           "mcp.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "oauth, err := client.MCP.OAuthLogin(ctx, codex.MCPOAuthLoginOptions{Name: \"github\"}); result, err := oauth.Wait(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationReason: mcpOAuthSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed MCP OAuth handle workflow routed by terminal completion notification; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "mcpServer/resource/read",
		ResourceOwner:         "MCP",
		WrapperName:           "MCP.ReadResource",
		WrapperFile:           "mcp.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.MCP.ReadResource(ctx, protocol.McpResourceReadParams{Server: \"github\", Uri: \"file:///README.md\"})",
		UnitTestOwner:         "mcp_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "mcpServer/tool/call",
		ResourceOwner:         "MCP",
		WrapperName:           "MCP.CallTool",
		WrapperFile:           "mcp.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.MCP.CallTool(ctx, protocol.McpServerToolCallParams{Server: \"github\", ThreadID: \"thread-id\", Tool: \"search\"})",
		UnitTestOwner:         "mcp_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "mcpServerStatus/list",
		ResourceOwner:         "MCP",
		WrapperName:           "MCP.ListStatus",
		WrapperFile:           "mcp.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.MCP.ListStatus(ctx, protocol.ListMcpServerStatusParams{})",
		UnitTestOwner:         "mcp_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "model/list",
		ResourceOwner:         "Models",
		WrapperName:           "Models.List",
		WrapperFile:           "models.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Models.List(ctx, protocol.ModelListParams{})",
		UnitTestOwner:         "models_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "modelProvider/capabilities/read",
		ResourceOwner:         "Models",
		WrapperName:           "Models.ReadProviderCapabilities",
		WrapperFile:           "models.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Models.ReadProviderCapabilities(ctx, protocol.ModelProviderCapabilitiesReadParams{})",
		UnitTestOwner:         "models_test.go",
		SafeIntegrationReason: stage5eSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "permissionProfile/list",
		ResourceOwner:         "PermissionProfiles",
		WrapperName:           "PermissionProfiles.List",
		WrapperFile:           "permission_profiles.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.PermissionProfiles.List(ctx, protocol.PermissionProfileListParams{Cwd: protocol.Some(\"/repo\")})",
		UnitTestOwner:         "permission_profiles_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/list",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.List",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.List(ctx, protocol.PluginListParams{})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/installed",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.Installed",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.Installed(ctx, protocol.PluginInstalledParams{})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/read",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.Read",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.Read(ctx, protocol.PluginReadParams{PluginName: \"plugin\"})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/skill/read",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.ReadSkill",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.ReadSkill(ctx, protocol.PluginSkillReadParams{RemoteMarketplaceName: \"marketplace\", RemotePluginID: \"plugin-id\", SkillName: \"skill\"})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/skills_hooks",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/share/save",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.SaveShare",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.SaveShare(ctx, protocol.PluginShareSaveParams{PluginPath: \"/repo/plugin\"})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/share/updateTargets",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.UpdateShareTargets",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.UpdateShareTargets(ctx, protocol.PluginShareUpdateTargetsParams{Discoverability: protocol.PluginShareUpdateDiscoverabilityPrivate, RemotePluginID: \"plugin-id\", ShareTargets: []protocol.PluginShareTarget{}})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/share/list",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.ListShares",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.ListShares(ctx, protocol.PluginShareListParams{})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/share/checkout",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.CheckoutShare",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.CheckoutShare(ctx, protocol.PluginShareCheckoutParams{RemotePluginID: \"plugin-id\"})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/share/delete",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.DeleteShare",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.DeleteShare(ctx, protocol.PluginShareDeleteParams{RemotePluginID: \"plugin-id\"})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/install",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.Install",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.Install(ctx, protocol.PluginInstallParams{PluginName: \"plugin\"})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "plugin/uninstall",
		ResourceOwner:         "Plugins",
		WrapperName:           "Plugins.Uninstall",
		WrapperFile:           "plugins.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Plugins.Uninstall(ctx, protocol.PluginUninstallParams{PluginID: \"plugin-id\"})",
		UnitTestOwner:         "plugins_test.go",
		SafeIntegrationReason: stage5dSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "review/start",
		ResourceOwner:         "Reviews",
		WrapperName:           "Reviews.Start / ReviewHandle",
		WrapperFile:           "reviews.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "review, err := client.Reviews.Start(ctx, codex.ReviewStartOptions{ThreadID: thread.ID(), Target: codex.UncommittedChangesReviewTarget()}); result, err := review.Wait(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/reviews",
		ReviewNote:            "typed review handle workflow owning reviewThreadId and turn.id from ReviewStartResponse, routing ordinary review turn lifecycle/result events; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "skills/list",
		ResourceOwner:         "Skills",
		WrapperName:           "Skills.List",
		WrapperFile:           "skills.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Skills.List(ctx, protocol.SkillsListParams{})",
		UnitTestOwner:         "skills_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/skills_hooks",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "skills/extraRoots/set",
		ResourceOwner:         "Skills",
		WrapperName:           "Skills.SetExtraRoots",
		WrapperFile:           "skills.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Skills.SetExtraRoots(ctx, protocol.SkillsExtraRootsSetParams{})",
		UnitTestOwner:         "skills_test.go",
		SafeIntegrationReason: skillsMutationSafeIntegrationReason,
		DocsExampleOwner:      "examples/skills_hooks",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "skills/config/write",
		ResourceOwner:         "Skills",
		WrapperName:           "Skills.WriteConfig",
		WrapperFile:           "skills.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Skills.WriteConfig(ctx, protocol.SkillsConfigWriteParams{})",
		UnitTestOwner:         "skills_test.go",
		SafeIntegrationReason: skillsMutationSafeIntegrationReason,
		DocsExampleOwner:      "examples/skills_hooks",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/start",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Start",
		WrapperFile:           "thread.go",
		SignatureConventionID: "high-level",
		CompileCallsite:       "client.Threads.Start(ctx, codex.ThreadStartOptions{CWD: \"/repo\", Permissions: \"workspace-write\"})",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/run",
		ReviewNote:            "high-level ergonomic workflow using root SDK options plus raw generated method",
	},
	{
		Method:                "thread/resume",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Resume",
		WrapperFile:           "thread.go",
		SignatureConventionID: "high-level",
		CompileCallsite:       "client.Threads.Resume(ctx, codex.ThreadResumeOptions{ThreadID: \"thread-id\"})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "high-level ergonomic workflow using root SDK options plus raw generated method",
	},
	{
		Method:                "thread/fork",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Fork",
		WrapperFile:           "thread.go",
		SignatureConventionID: "high-level",
		CompileCallsite:       "client.Threads.Fork(ctx, codex.ThreadForkOptions{ThreadID: \"thread-id\"})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "high-level ergonomic workflow using root SDK options plus raw generated method",
	},
	{
		Method:                "thread/archive",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Archive",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.Archive(ctx, protocol.ThreadArchiveParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/delete",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Delete",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.Delete(ctx, protocol.ThreadDeleteParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: "destructive thread mutation requires isolated CODEX_HOME fixture to avoid user data loss",
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/unsubscribe",
		ResourceOwner:         "Threads",
		WrapperName:           "Thread.Unsubscribe",
		WrapperFile:           "thread.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "thread.Unsubscribe(ctx)",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "typed handle workflow; handle injects thread identity",
	},
	{
		Method:                "thread/name/set",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.SetName",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.SetName(ctx, protocol.ThreadSetNameParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/goal/set",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.SetGoal",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.SetGoal(ctx, protocol.ThreadGoalSetParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/goal/get",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.GetGoal",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.GetGoal(ctx, protocol.ThreadGoalGetParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/goal/clear",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.ClearGoal",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.ClearGoal(ctx, protocol.ThreadGoalClearParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/metadata/update",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.UpdateMetadata",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.UpdateMetadata(ctx, protocol.ThreadMetadataUpdateParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/unarchive",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Unarchive",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.Unarchive(ctx, protocol.ThreadUnarchiveParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/compact/start",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.StartCompaction",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.StartCompaction(ctx, protocol.ThreadCompactStartParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/shellCommand",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.ShellCommand",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.ShellCommand(ctx, protocol.ThreadShellCommandParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/approveGuardianDeniedAction",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.ApproveGuardianDeniedAction",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.ApproveGuardianDeniedAction(ctx, protocol.ThreadApproveGuardianDeniedActionParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/rollback",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Rollback",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.Rollback(ctx, protocol.ThreadRollbackParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: "destructive thread mutation requires isolated CODEX_HOME fixture to avoid user data loss",
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/list",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.List",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.List(ctx, protocol.ThreadListParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/loaded/list",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.ListLoaded",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.ListLoaded(ctx, protocol.ThreadLoadedListParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/read",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Read",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.Read(ctx, protocol.ThreadReadParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/raw_protocol",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/inject_items",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.InjectItems",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.InjectItems(ctx, protocol.ThreadInjectItemsParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "turn/start",
		ResourceOwner:         "Turns",
		WrapperName:           "Thread.Run / Thread.Turn / TurnHandle.Stream",
		WrapperFile:           "turn.go",
		SignatureConventionID: "high-level",
		CompileCallsite:       "thread.Run(ctx, codex.Text(\"inspect this repo\"), codex.TurnOptions{Model: \"gpt-5.4\"}); turn, err := thread.Turn(ctx, codex.Text(\"continue\"), codex.TurnOptions{}); stream, err := turn.Stream(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationOwner:  "real_app_server_test.go",
		DocsExampleOwner:      "examples/run",
		ReviewNote:            "high-level ergonomic workflow using root SDK input/options plus raw generated method",
	},
	{
		Method:                "turn/steer",
		ResourceOwner:         "Turns",
		WrapperName:           "TurnHandle.Steer",
		WrapperFile:           "turn.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "turn.Steer(ctx, codex.Text(\"steer toward tests\"))",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/streaming",
		ReviewNote:            "typed handle workflow using root SDK input helpers; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "turn/interrupt",
		ResourceOwner:         "Turns",
		WrapperName:           "TurnHandle.Interrupt",
		WrapperFile:           "turn.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "turn.Interrupt(ctx)",
		UnitTestOwner:         "workflows_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/streaming",
		ReviewNote:            "typed handle workflow",
	},
	{
		Method:                "windowsSandbox/setupStart",
		ResourceOwner:         "WindowsSandbox",
		WrapperName:           "WindowsSandbox.SetupStart",
		WrapperFile:           "windows_sandbox.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.WindowsSandbox.SetupStart(ctx, protocol.WindowsSandboxSetupStartParams{Mode: protocol.WindowsSandboxSetupModeUnelevated})",
		UnitTestOwner:         "windows_sandbox_test.go",
		SafeIntegrationReason: stage5fWindowsSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "public wrapper with typed unsupported-platform error on non-Windows app-server runtimes",
	},
	{
		Method:                "windowsSandbox/readiness",
		ResourceOwner:         "WindowsSandbox",
		WrapperName:           "WindowsSandbox.Readiness",
		WrapperFile:           "windows_sandbox.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.WindowsSandbox.Readiness(ctx)",
		UnitTestOwner:         "windows_sandbox_test.go",
		SafeIntegrationReason: stage5fWindowsSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "public wrapper with typed unsupported-platform readiness status on non-Windows app-server runtimes",
	},
	{
		Method:                "thread/realtime/start",
		ResourceOwner:         "Realtime",
		WrapperName:           "Realtime.Start / realtime handle",
		WrapperFile:           "realtime.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "session, start, err := client.Realtime.Start(ctx, codex.RealtimeStartOptions{ThreadID: thread.ID()})",
		UnitTestOwner:         "realtime_test.go",
		SafeIntegrationReason: realtimeSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; SDK owns realtime session handle identity where the manifest marks it client-supplied; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "thread/realtime/appendAudio",
		ResourceOwner:         "Realtime",
		WrapperName:           "RealtimeSession.AppendAudio",
		WrapperFile:           "realtime.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "session.AppendAudio(ctx, codex.AudioChunk{Data: audio})",
		UnitTestOwner:         "realtime_test.go",
		SafeIntegrationReason: realtimeSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects thread identity while current protocol lacks follow-up session identity",
	},
	{
		Method:                "thread/realtime/appendText",
		ResourceOwner:         "Realtime",
		WrapperName:           "RealtimeSession.AppendText",
		WrapperFile:           "realtime.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "session.AppendText(ctx, \"hello\")",
		UnitTestOwner:         "realtime_test.go",
		SafeIntegrationReason: realtimeSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects thread identity while current protocol lacks follow-up session identity",
	},
	{
		Method:                "thread/realtime/appendSpeech",
		ResourceOwner:         "Realtime",
		WrapperName:           "RealtimeSession.AppendSpeech",
		WrapperFile:           "realtime.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "session.AppendSpeech(ctx, codex.SpeechInput{Text: \"hello\"})",
		UnitTestOwner:         "realtime_test.go",
		SafeIntegrationReason: realtimeSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects thread identity while current protocol lacks follow-up session identity",
	},
	{
		Method:                "thread/realtime/stop",
		ResourceOwner:         "Realtime",
		WrapperName:           "RealtimeSession.Stop",
		WrapperFile:           "realtime.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "session.Stop(ctx)",
		UnitTestOwner:         "realtime_test.go",
		SafeIntegrationReason: realtimeSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow",
	},
	{
		Method:                "thread/realtime/listVoices",
		ResourceOwner:         "Realtime",
		WrapperName:           "Realtime.ListVoices",
		WrapperFile:           "realtime.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Realtime.ListVoices(ctx, protocol.ThreadRealtimeListVoicesParams{})",
		UnitTestOwner:         "realtime_test.go",
		SafeIntegrationReason: realtimeSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/increment_elicitation",
		ResourceOwner:         "Threads",
		WrapperName:           "Thread.IncrementElicitation / Threads.IncrementElicitation",
		WrapperFile:           "thread.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "thread.IncrementElicitation(ctx); client.Threads.IncrementElicitation(ctx, thread.ID())",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "typed handle workflow; handle method injects thread identity, root resource method accepts thread identity without exposing raw params",
	},
	{
		Method:                "thread/decrement_elicitation",
		ResourceOwner:         "Threads",
		WrapperName:           "Thread.DecrementElicitation / Threads.DecrementElicitation",
		WrapperFile:           "thread.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "thread.DecrementElicitation(ctx); client.Threads.DecrementElicitation(ctx, thread.ID())",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "typed handle workflow; handle method injects thread identity, root resource method accepts thread identity without exposing raw params",
	},
	{
		Method:                "thread/settings/update",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.UpdateSettings",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.UpdateSettings(ctx, protocol.ThreadSettingsUpdateParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/memoryMode/set",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.SetMemoryMode",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.SetMemoryMode(ctx, protocol.ThreadMemoryModeSetParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/backgroundTerminals/clean",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.CleanBackgroundTerminals",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.CleanBackgroundTerminals(ctx, protocol.ThreadBackgroundTerminalsCleanParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/backgroundTerminals/list",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.ListBackgroundTerminals",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.ListBackgroundTerminals(ctx, protocol.ThreadBackgroundTerminalsListParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/backgroundTerminals/terminate",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.TerminateBackgroundTerminal",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.TerminateBackgroundTerminal(ctx, protocol.ThreadBackgroundTerminalsTerminateParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/search",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.Search",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.Search(ctx, protocol.ThreadSearchParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/turns/list",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.ListTurns",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.ListTurns(ctx, protocol.ThreadTurnsListParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "thread/items/list",
		ResourceOwner:         "Threads",
		WrapperName:           "Threads.ListItems",
		WrapperFile:           "thread.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Threads.ListItems(ctx, protocol.ThreadItemsListParams{})",
		UnitTestOwner:         "thread_test.go",
		SafeIntegrationReason: lifecycleSafeIntegrationReason,
		DocsExampleOwner:      "README thread lifecycle",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "memory/reset",
		ResourceOwner:         "Memory",
		WrapperName:           "Memory.Reset",
		WrapperFile:           "memory.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Memory.Reset(ctx)",
		UnitTestOwner:         "memory_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "collaborationMode/list",
		ResourceOwner:         "CollaborationModes",
		WrapperName:           "CollaborationModes.List",
		WrapperFile:           "collaboration_modes.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.CollaborationModes.List(ctx, protocol.CollaborationModeListParams{})",
		UnitTestOwner:         "collaboration_modes_test.go",
		SafeIntegrationReason: stage5eSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "remoteControl/enable",
		ResourceOwner:         "RemoteControl",
		WrapperName:           "RemoteControl.Enable",
		WrapperFile:           "remote_control.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.RemoteControl.Enable(ctx, protocol.NullableRemoteControlEnableParams{})",
		UnitTestOwner:         "remote_control_test.go",
		SafeIntegrationReason: stage5eRemoteSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "public wrapper, live workflow requires paired CI environment",
	},
	{
		Method:                "remoteControl/disable",
		ResourceOwner:         "RemoteControl",
		WrapperName:           "RemoteControl.Disable",
		WrapperFile:           "remote_control.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.RemoteControl.Disable(ctx, protocol.NullableRemoteControlDisableParams{})",
		UnitTestOwner:         "remote_control_test.go",
		SafeIntegrationReason: stage5eRemoteSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "public wrapper, live workflow requires paired CI environment",
	},
	{
		Method:                "remoteControl/status/read",
		ResourceOwner:         "RemoteControl",
		WrapperName:           "RemoteControl.ReadStatus",
		WrapperFile:           "remote_control.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.RemoteControl.ReadStatus(ctx)",
		UnitTestOwner:         "remote_control_test.go",
		SafeIntegrationReason: stage5eRemoteSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "public wrapper, live workflow requires paired CI environment",
	},
	{
		Method:                "remoteControl/pairing/start",
		ResourceOwner:         "RemoteControl",
		WrapperName:           "RemoteControl.StartPairing / RemoteControlPairingHandle",
		WrapperFile:           "remote_control.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "pairing, start, err := client.RemoteControl.StartPairing(ctx, codex.RemoteControlPairingOptions{ManualCode: true})",
		UnitTestOwner:         "remote_control_test.go",
		SafeIntegrationReason: stage5eRemoteSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed pairing handle workflow; handle owns pairing code/session data; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "remoteControl/pairing/status",
		ResourceOwner:         "RemoteControl",
		WrapperName:           "RemoteControlPairingHandle.Status / RemoteControl.PairingStatus",
		WrapperFile:           "remote_control.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "status, err := pairing.Status(ctx); status, err = client.RemoteControl.PairingStatus(ctx, pairing.ID())",
		UnitTestOwner:         "remote_control_test.go",
		SafeIntegrationReason: stage5eRemoteSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed pairing handle workflow; handle injects pairing identity when protocol exposes one, otherwise root method accepts the start-returned pairing code/session token without exposing raw params",
	},
	{
		Method:                "remoteControl/client/list",
		ResourceOwner:         "RemoteControl",
		WrapperName:           "RemoteControl.ListClients",
		WrapperFile:           "remote_control.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.RemoteControl.ListClients(ctx, protocol.RemoteControlClientsListParams{EnvironmentID: \"env-1\"})",
		UnitTestOwner:         "remote_control_test.go",
		SafeIntegrationReason: stage5eRemoteSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "public wrapper, live workflow requires paired CI environment",
	},
	{
		Method:                "remoteControl/client/revoke",
		ResourceOwner:         "RemoteControl",
		WrapperName:           "RemoteControl.RevokeClient",
		WrapperFile:           "remote_control.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.RemoteControl.RevokeClient(ctx, protocol.RemoteControlClientsRevokeParams{ClientID: \"client-1\", EnvironmentID: \"env-1\"})",
		UnitTestOwner:         "remote_control_test.go",
		SafeIntegrationReason: stage5eRemoteSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "public wrapper, live workflow requires paired CI environment",
	},
	{
		Method:                "environment/add",
		ResourceOwner:         "Environments",
		WrapperName:           "Environments.Add",
		WrapperFile:           "environments.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Environments.Add(ctx, protocol.EnvironmentAddParams{EnvironmentID: \"env-1\", ExecServerURL: \"http://127.0.0.1:9876\"})",
		UnitTestOwner:         "environments_test.go",
		SafeIntegrationReason: stage5eSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "environment/info",
		ResourceOwner:         "Environments",
		WrapperName:           "Environments.Info",
		WrapperFile:           "environments.go",
		SignatureConventionID: "thin",
		CompileCallsite:       "client.Environments.Info(ctx, protocol.EnvironmentInfoParams{EnvironmentID: \"env-1\"})",
		UnitTestOwner:         "environments_test.go",
		SafeIntegrationReason: stage5eSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "SDK-public thin wrapper",
	},
	{
		Method:                "process/spawn",
		ResourceOwner:         "Processes",
		WrapperName:           "Processes.Spawn / process handle",
		WrapperFile:           "processes.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "proc, start, err := client.Processes.Spawn(ctx, codex.ProcessSpawnOptions{Command: []string{\"echo\", \"ok\"}, CWD: \"/repo\"})",
		UnitTestOwner:         "processes_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; SDK generates/injects process handle identity; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "process/writeStdin",
		ResourceOwner:         "Processes",
		WrapperName:           "ProcessHandle.WriteStdin / CloseStdin",
		WrapperFile:           "processes.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "proc.WriteStdin(ctx, []byte(\"input\")); proc.CloseStdin(ctx)",
		UnitTestOwner:         "processes_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects process identity",
	},
	{
		Method:                "process/kill",
		ResourceOwner:         "Processes",
		WrapperName:           "ProcessHandle.Kill",
		WrapperFile:           "processes.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "proc.Kill(ctx)",
		UnitTestOwner:         "processes_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects process identity",
	},
	{
		Method:                "process/resizePty",
		ResourceOwner:         "Processes",
		WrapperName:           "ProcessHandle.ResizePTY",
		WrapperFile:           "processes.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "proc.ResizePTY(ctx, codex.TerminalSize{Rows: 24, Cols: 80})",
		UnitTestOwner:         "processes_test.go",
		SafeIntegrationReason: stage5cSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects process identity",
	},
	{
		Method:                "fuzzyFileSearch/sessionStart",
		ResourceOwner:         "FuzzyFileSearch",
		WrapperName:           "FuzzyFileSearch.StartSession",
		WrapperFile:           "fuzzy_file_search.go",
		SignatureConventionID: "handle-start",
		CompileCallsite:       "session, err := client.FuzzyFileSearch.StartSession(ctx, codex.FuzzySearchSessionOptions{Roots: []string{\".\"}})",
		UnitTestOwner:         "fuzzy_file_search_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; SDK generates/injects session identity; raw params only through generated raw protocol APIs",
	},
	{
		Method:                "fuzzyFileSearch/sessionUpdate",
		ResourceOwner:         "FuzzyFileSearch",
		WrapperName:           "FuzzySearchSession.Update",
		WrapperFile:           "fuzzy_file_search.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "session.Update(ctx, codex.FuzzySearchUpdate{Query: \"main.go\"})",
		UnitTestOwner:         "fuzzy_file_search_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow; handle injects session identity",
	},
	{
		Method:                "fuzzyFileSearch/sessionStop",
		ResourceOwner:         "FuzzyFileSearch",
		WrapperName:           "FuzzySearchSession.Close",
		WrapperFile:           "fuzzy_file_search.go",
		SignatureConventionID: "handle-followup",
		CompileCallsite:       "session.Close(ctx)",
		UnitTestOwner:         "fuzzy_file_search_test.go",
		SafeIntegrationReason: stage5fSafeIntegrationReason,
		DocsExampleOwner:      "examples/resources",
		ReviewNote:            "typed handle workflow",
	},
	{
		Method:                 "mock/experimentalMethod",
		ResourceOwner:          "internal test only",
		WrapperFile:            "raw_test.go",
		SignatureConventionID:  "internal-test-only",
		UnitTestOwner:          "raw_test.go",
		SafeIntegrationReason:  "internal test only",
		DocsExampleOwner:       "none; test-only manifest exception",
		GeneratedOnlyException: "internal test-only manifest exception; no public API/docs/raw method",
		ReviewNote:             "internal test-only manifest exception; no public API/docs/raw method",
	},
	{
		Method:                 "initialize",
		ResourceOwner:          "handshake",
		SignatureConventionID:  "handshake-only",
		UnitTestOwner:          "compatibility_test.go",
		DocsExampleOwner:       "internal handshake manifest exception only; no public raw/resource docs",
		GeneratedOnlyException: "no public Raw().Initialize or resource wrapper",
		ReviewNote:             "NewClient owns initialize and generated initialized",
	},
	{
		Method:                 "getConversationSummary",
		ResourceOwner:          "compatibility",
		SignatureConventionID:  "compatibility-only",
		UnitTestOwner:          "raw_test.go",
		DocsExampleOwner:       "internal manifest exception only; no public docs/examples",
		GeneratedOnlyException: "internal compatibility dispatch/decode only; no public Raw() method",
		ReviewNote:             "deprecated v1 compatibility surface",
	},
	{
		Method:                 "gitDiffToRemote",
		ResourceOwner:          "compatibility",
		SignatureConventionID:  "compatibility-only",
		UnitTestOwner:          "raw_test.go",
		DocsExampleOwner:       "internal manifest exception only; no public docs/examples",
		GeneratedOnlyException: "internal compatibility dispatch/decode only; no public Raw() method",
		ReviewNote:             "deprecated v1 compatibility surface",
	},
	{
		Method:                 "getAuthStatus",
		ResourceOwner:          "compatibility",
		SignatureConventionID:  "compatibility-only",
		UnitTestOwner:          "raw_test.go",
		DocsExampleOwner:       "internal manifest exception only; no public docs/examples",
		GeneratedOnlyException: "internal compatibility dispatch/decode only; no public Raw() method",
		ReviewNote:             "deprecated in favor of account/read",
	},
}

var serverHandlerMappings = []ServerHandlerMapping{
	{
		Method:           "account/chatgptAuthTokens/refresh",
		HandlerOwner:     "ServerHandlers.ChatGPTTokenRefresh",
		Visibility:       "sdk-public",
		Capability:       "chatgpt-token-refresh",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "README server handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:                 "applyPatchApproval",
		HandlerOwner:           "internal compatibility dispatch/decode only; no public handler field",
		Visibility:             "compatibility-only",
		Capability:             "legacy-apply-patch-approval",
		UnitTestOwner:          "server_handlers_test.go",
		DocsExampleOwner:       "internal manifest exception only; no public docs/examples",
		GeneratedOnlyException: "internal compatibility dispatch/decode only; no public handler field",
		ReviewNote:             "deprecated v1 compatibility request",
	},
	{
		Method:           "attestation/generate",
		HandlerOwner:     "ServerHandlers.Attestation",
		Visibility:       "sdk-public",
		Capability:       "attestation-generate",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "README server handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:                 "execCommandApproval",
		HandlerOwner:           "internal compatibility dispatch/decode only; no public handler field",
		Visibility:             "compatibility-only",
		Capability:             "legacy-exec-command-approval",
		UnitTestOwner:          "server_handlers_test.go",
		DocsExampleOwner:       "internal manifest exception only; no public docs/examples",
		GeneratedOnlyException: "internal compatibility dispatch/decode only; no public handler field",
		ReviewNote:             "deprecated v1 compatibility request",
	},
	{
		Method:           "item/commandExecution/requestApproval",
		HandlerOwner:     "ServerHandlers.Approvals",
		Visibility:       "sdk-public",
		Capability:       "command-execution-approval",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "examples/server_handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:           "item/fileChange/requestApproval",
		HandlerOwner:     "ServerHandlers.Approvals",
		Visibility:       "sdk-public",
		Capability:       "file-change-approval",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "examples/server_handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:           "item/tool/requestUserInput",
		HandlerOwner:     "ServerHandlers.UserInput",
		Visibility:       "sdk-public",
		Capability:       "tool-user-input",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "examples/server_handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:           "item/permissions/requestApproval",
		HandlerOwner:     "ServerHandlers.Permissions",
		Visibility:       "sdk-public",
		Capability:       "permission-approval",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "examples/server_handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:           "item/tool/call",
		HandlerOwner:     "ServerHandlers.DynamicTools",
		Visibility:       "sdk-public",
		Capability:       "dynamic-tool-call",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "examples/server_handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:           "mcpServer/elicitation/request",
		HandlerOwner:     "ServerHandlers.MCPElicitation",
		Visibility:       "sdk-public",
		Capability:       "mcp-elicitation",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "examples/server_handlers",
		ReviewNote:       "public handler",
	},
	{
		Method:           "currentTime/read",
		HandlerOwner:     "ServerHandlers.CurrentTime",
		Visibility:       "experimental-public",
		Capability:       "current-time-read",
		UnitTestOwner:    "server_handlers_test.go",
		DocsExampleOwner: "README experimental server handlers",
		ReviewNote:       "experimental public handler; default behavior may return typed unsupported error when unset",
	},
}
