package protocol

const StableProtocolDigest = "ffeab0733adaaf9f98aa2b8d7964e29b03792ee47a7bd62eedeff57293950fe9"
const StableSchemaDigest = "01d788c9c33d7ae40965fe65289bd47cb4142a438cb43ed3cf1b7254305238e7"
const StableManifestDigest = "39948b3b8d28d2b4c464964b89e8e58cf24b827b00d300a557ee2667d851c1c8"
const ExperimentalProtocolDigest = "fbedd64121f2107f1f95d913f147a6c1e14125ebd6d428e75143de801ab2a341"
const ExperimentalSchemaDigest = "b7646a75890b517468df186764bf20ca61bd43b718adfa45aa1b5f1a44a814ed"
const ExperimentalManifestDigest = "a1d38a9c4b4bf599ff10f561ab46aae7ea1acac0862ba9ef1da33a3f9604662d"

type ExperimentalFieldMetadata struct {
	ContainingType    string
	FieldPath         string
	Reason            string
	InspectParams     bool
	DiscriminatorJSON string
}

type BoundedModelContextFieldMetadata struct {
	Method       string
	FieldPath    string
	LimitProfile string
}

type MethodMetadata struct {
	Method                    string
	Visibility                string
	ParamsType                string
	ResponseType              string
	ParamsSchemaRef           string
	ResponseSchemaRef         string
	SchemaExcludedReason      string
	InspectParams             bool
	ManualPayloadConversion   string
	Experimental              bool
	Retry                     string
	BoundedModelContextFields []BoundedModelContextFieldMetadata
	ExperimentalFields        []ExperimentalFieldMetadata
}

var MethodMetadataByMethod = map[string]MethodMetadata{
	"initialize":                               {Method: "initialize", Visibility: "handshakeOnly", ParamsType: "InitializeParams", ResponseType: "InitializeResponse", ParamsSchemaRef: "#/definitions/InitializeParams", ResponseSchemaRef: "#/definitions/InitializeResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/start":                             {Method: "thread/start", Visibility: "public", ParamsType: "ThreadStartParams", ResponseType: "ThreadStartResponse", ParamsSchemaRef: "#/definitions/ThreadStartParams", ResponseSchemaRef: "#/definitions/ThreadStartResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "ThreadStartParams", FieldPath: "allow_provider_model_fallback", Reason: "thread/start.allowProviderModelFallback", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "runtime_workspace_roots", Reason: "thread/start.runtimeWorkspaceRoots", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "approval_policy", Reason: "nested", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "permissions", Reason: "thread/start.permissions", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "multi_agent_mode", Reason: "thread/start.multiAgentMode", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "history_mode", Reason: "thread/start.historyMode", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "environments", Reason: "thread/start.environments", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "dynamic_tools", Reason: "thread/start.dynamicTools", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "selected_capability_roots", Reason: "thread/start.selectedCapabilityRoots", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "mock_experimental_field", Reason: "thread/start.mockExperimentalField", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartParams", FieldPath: "experimental_raw_events", Reason: "thread/start.experimentalRawEvents", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartResponse", FieldPath: "runtime_workspace_roots", Reason: "thread/start.runtimeWorkspaceRoots", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartResponse", FieldPath: "approval_policy", Reason: "nested", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartResponse", FieldPath: "active_permission_profile", Reason: "thread/start.activePermissionProfile", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadStartResponse", FieldPath: "multi_agent_mode", Reason: "thread/start.multiAgentMode", InspectParams: false, DiscriminatorJSON: ""}}},
	"thread/resume":                            {Method: "thread/resume", Visibility: "public", ParamsType: "ThreadResumeParams", ResponseType: "ThreadResumeResponse", ParamsSchemaRef: "#/definitions/ThreadResumeParams", ResponseSchemaRef: "#/definitions/ThreadResumeResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "ThreadResumeParams", FieldPath: "history", Reason: "thread/resume.history", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeParams", FieldPath: "path", Reason: "thread/resume.path", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeParams", FieldPath: "runtime_workspace_roots", Reason: "thread/resume.runtimeWorkspaceRoots", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeParams", FieldPath: "approval_policy", Reason: "nested", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeParams", FieldPath: "permissions", Reason: "thread/resume.permissions", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeParams", FieldPath: "exclude_turns", Reason: "thread/resume.excludeTurns", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeParams", FieldPath: "initial_turns_page", Reason: "thread/resume.initialTurnsPage", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeResponse", FieldPath: "runtime_workspace_roots", Reason: "thread/resume.runtimeWorkspaceRoots", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeResponse", FieldPath: "approval_policy", Reason: "nested", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeResponse", FieldPath: "active_permission_profile", Reason: "thread/resume.activePermissionProfile", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeResponse", FieldPath: "multi_agent_mode", Reason: "thread/resume.multiAgentMode", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadResumeResponse", FieldPath: "initial_turns_page", Reason: "thread/resume.initialTurnsPage", InspectParams: false, DiscriminatorJSON: ""}}},
	"thread/fork":                              {Method: "thread/fork", Visibility: "public", ParamsType: "ThreadForkParams", ResponseType: "ThreadForkResponse", ParamsSchemaRef: "#/definitions/ThreadForkParams", ResponseSchemaRef: "#/definitions/ThreadForkResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "ThreadForkParams", FieldPath: "path", Reason: "thread/fork.path", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkParams", FieldPath: "runtime_workspace_roots", Reason: "thread/fork.runtimeWorkspaceRoots", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkParams", FieldPath: "approval_policy", Reason: "nested", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkParams", FieldPath: "permissions", Reason: "thread/fork.permissions", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkParams", FieldPath: "exclude_turns", Reason: "thread/fork.excludeTurns", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkResponse", FieldPath: "runtime_workspace_roots", Reason: "thread/fork.runtimeWorkspaceRoots", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkResponse", FieldPath: "approval_policy", Reason: "nested", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkResponse", FieldPath: "active_permission_profile", Reason: "thread/fork.activePermissionProfile", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ThreadForkResponse", FieldPath: "multi_agent_mode", Reason: "thread/fork.multiAgentMode", InspectParams: false, DiscriminatorJSON: ""}}},
	"thread/archive":                           {Method: "thread/archive", Visibility: "public", ParamsType: "ThreadArchiveParams", ResponseType: "ThreadArchiveResponse", ParamsSchemaRef: "#/definitions/ThreadArchiveParams", ResponseSchemaRef: "#/definitions/ThreadArchiveResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/delete":                            {Method: "thread/delete", Visibility: "public", ParamsType: "ThreadDeleteParams", ResponseType: "ThreadDeleteResponse", ParamsSchemaRef: "#/definitions/ThreadDeleteParams", ResponseSchemaRef: "#/definitions/ThreadDeleteResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/unsubscribe":                       {Method: "thread/unsubscribe", Visibility: "public", ParamsType: "ThreadUnsubscribeParams", ResponseType: "ThreadUnsubscribeResponse", ParamsSchemaRef: "#/definitions/ThreadUnsubscribeParams", ResponseSchemaRef: "#/definitions/ThreadUnsubscribeResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/increment_elicitation":             {Method: "thread/increment_elicitation", Visibility: "public", ParamsType: "ThreadIncrementElicitationParams", ResponseType: "ThreadIncrementElicitationResponse", ParamsSchemaRef: "#/definitions/ThreadIncrementElicitationParams", ResponseSchemaRef: "#/definitions/ThreadIncrementElicitationResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/decrement_elicitation":             {Method: "thread/decrement_elicitation", Visibility: "public", ParamsType: "ThreadDecrementElicitationParams", ResponseType: "ThreadDecrementElicitationResponse", ParamsSchemaRef: "#/definitions/ThreadDecrementElicitationParams", ResponseSchemaRef: "#/definitions/ThreadDecrementElicitationResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/name/set":                          {Method: "thread/name/set", Visibility: "public", ParamsType: "ThreadSetNameParams", ResponseType: "ThreadSetNameResponse", ParamsSchemaRef: "#/definitions/ThreadSetNameParams", ResponseSchemaRef: "#/definitions/ThreadSetNameResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/goal/set":                          {Method: "thread/goal/set", Visibility: "public", ParamsType: "ThreadGoalSetParams", ResponseType: "ThreadGoalSetResponse", ParamsSchemaRef: "#/definitions/ThreadGoalSetParams", ResponseSchemaRef: "#/definitions/ThreadGoalSetResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/goal/get":                          {Method: "thread/goal/get", Visibility: "public", ParamsType: "ThreadGoalGetParams", ResponseType: "ThreadGoalGetResponse", ParamsSchemaRef: "#/definitions/ThreadGoalGetParams", ResponseSchemaRef: "#/definitions/ThreadGoalGetResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/goal/clear":                        {Method: "thread/goal/clear", Visibility: "public", ParamsType: "ThreadGoalClearParams", ResponseType: "ThreadGoalClearResponse", ParamsSchemaRef: "#/definitions/ThreadGoalClearParams", ResponseSchemaRef: "#/definitions/ThreadGoalClearResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/metadata/update":                   {Method: "thread/metadata/update", Visibility: "public", ParamsType: "ThreadMetadataUpdateParams", ResponseType: "ThreadMetadataUpdateResponse", ParamsSchemaRef: "#/definitions/ThreadMetadataUpdateParams", ResponseSchemaRef: "#/definitions/ThreadMetadataUpdateResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/settings/update":                   {Method: "thread/settings/update", Visibility: "public", ParamsType: "ThreadSettingsUpdateParams", ResponseType: "ThreadSettingsUpdateResponse", ParamsSchemaRef: "#/definitions/ThreadSettingsUpdateParams", ResponseSchemaRef: "#/definitions/ThreadSettingsUpdateResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "ThreadSettingsUpdateParams", FieldPath: "approval_policy", Reason: "nested", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadSettingsUpdateParams", FieldPath: "permissions", Reason: "thread/settings/update.permissions", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadSettingsUpdateParams", FieldPath: "collaboration_mode", Reason: "thread/settings/update.collaborationMode", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadSettingsUpdateParams", FieldPath: "multi_agent_mode", Reason: "thread/settings/update.multiAgentMode", InspectParams: true, DiscriminatorJSON: ""}}},
	"thread/memoryMode/set":                    {Method: "thread/memoryMode/set", Visibility: "public", ParamsType: "ThreadMemoryModeSetParams", ResponseType: "ThreadMemoryModeSetResponse", ParamsSchemaRef: "#/definitions/ThreadMemoryModeSetParams", ResponseSchemaRef: "#/definitions/ThreadMemoryModeSetResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"memory/reset":                             {Method: "memory/reset", Visibility: "public", ParamsType: "Option<()>", ResponseType: "MemoryResetResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/MemoryResetResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/unarchive":                         {Method: "thread/unarchive", Visibility: "public", ParamsType: "ThreadUnarchiveParams", ResponseType: "ThreadUnarchiveResponse", ParamsSchemaRef: "#/definitions/ThreadUnarchiveParams", ResponseSchemaRef: "#/definitions/ThreadUnarchiveResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/compact/start":                     {Method: "thread/compact/start", Visibility: "public", ParamsType: "ThreadCompactStartParams", ResponseType: "ThreadCompactStartResponse", ParamsSchemaRef: "#/definitions/ThreadCompactStartParams", ResponseSchemaRef: "#/definitions/ThreadCompactStartResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/shellCommand":                      {Method: "thread/shellCommand", Visibility: "public", ParamsType: "ThreadShellCommandParams", ResponseType: "ThreadShellCommandResponse", ParamsSchemaRef: "#/definitions/ThreadShellCommandParams", ResponseSchemaRef: "#/definitions/ThreadShellCommandResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/approveGuardianDeniedAction":       {Method: "thread/approveGuardianDeniedAction", Visibility: "public", ParamsType: "ThreadApproveGuardianDeniedActionParams", ResponseType: "ThreadApproveGuardianDeniedActionResponse", ParamsSchemaRef: "#/definitions/ThreadApproveGuardianDeniedActionParams", ResponseSchemaRef: "#/definitions/ThreadApproveGuardianDeniedActionResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/backgroundTerminals/clean":         {Method: "thread/backgroundTerminals/clean", Visibility: "public", ParamsType: "ThreadBackgroundTerminalsCleanParams", ResponseType: "ThreadBackgroundTerminalsCleanResponse", ParamsSchemaRef: "#/definitions/ThreadBackgroundTerminalsCleanParams", ResponseSchemaRef: "#/definitions/ThreadBackgroundTerminalsCleanResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/backgroundTerminals/list":          {Method: "thread/backgroundTerminals/list", Visibility: "public", ParamsType: "ThreadBackgroundTerminalsListParams", ResponseType: "ThreadBackgroundTerminalsListResponse", ParamsSchemaRef: "#/definitions/ThreadBackgroundTerminalsListParams", ResponseSchemaRef: "#/definitions/ThreadBackgroundTerminalsListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/backgroundTerminals/terminate":     {Method: "thread/backgroundTerminals/terminate", Visibility: "public", ParamsType: "ThreadBackgroundTerminalsTerminateParams", ResponseType: "ThreadBackgroundTerminalsTerminateResponse", ParamsSchemaRef: "#/definitions/ThreadBackgroundTerminalsTerminateParams", ResponseSchemaRef: "#/definitions/ThreadBackgroundTerminalsTerminateResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/rollback":                          {Method: "thread/rollback", Visibility: "public", ParamsType: "ThreadRollbackParams", ResponseType: "ThreadRollbackResponse", ParamsSchemaRef: "#/definitions/ThreadRollbackParams", ResponseSchemaRef: "#/definitions/ThreadRollbackResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/list":                              {Method: "thread/list", Visibility: "public", ParamsType: "ThreadListParams", ResponseType: "ThreadListResponse", ParamsSchemaRef: "#/definitions/ThreadListParams", ResponseSchemaRef: "#/definitions/ThreadListResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "ThreadListParams", FieldPath: "parent_thread_id", Reason: "thread/list.parentThreadId", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "ThreadListParams", FieldPath: "ancestor_thread_id", Reason: "thread/list.ancestorThreadId", InspectParams: true, DiscriminatorJSON: ""}}},
	"thread/search":                            {Method: "thread/search", Visibility: "public", ParamsType: "ThreadSearchParams", ResponseType: "ThreadSearchResponse", ParamsSchemaRef: "#/definitions/ThreadSearchParams", ResponseSchemaRef: "#/definitions/ThreadSearchResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/loaded/list":                       {Method: "thread/loaded/list", Visibility: "public", ParamsType: "ThreadLoadedListParams", ResponseType: "ThreadLoadedListResponse", ParamsSchemaRef: "#/definitions/ThreadLoadedListParams", ResponseSchemaRef: "#/definitions/ThreadLoadedListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/read":                              {Method: "thread/read", Visibility: "public", ParamsType: "ThreadReadParams", ResponseType: "ThreadReadResponse", ParamsSchemaRef: "#/definitions/ThreadReadParams", ResponseSchemaRef: "#/definitions/ThreadReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/turns/list":                        {Method: "thread/turns/list", Visibility: "public", ParamsType: "ThreadTurnsListParams", ResponseType: "ThreadTurnsListResponse", ParamsSchemaRef: "#/definitions/ThreadTurnsListParams", ResponseSchemaRef: "#/definitions/ThreadTurnsListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/items/list":                        {Method: "thread/items/list", Visibility: "public", ParamsType: "ThreadItemsListParams", ResponseType: "ThreadItemsListResponse", ParamsSchemaRef: "#/definitions/ThreadItemsListParams", ResponseSchemaRef: "#/definitions/ThreadItemsListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/inject_items":                      {Method: "thread/inject_items", Visibility: "public", ParamsType: "ThreadInjectItemsParams", ResponseType: "ThreadInjectItemsResponse", ParamsSchemaRef: "#/definitions/ThreadInjectItemsParams", ResponseSchemaRef: "#/definitions/ThreadInjectItemsResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"skills/list":                              {Method: "skills/list", Visibility: "public", ParamsType: "SkillsListParams", ResponseType: "SkillsListResponse", ParamsSchemaRef: "#/definitions/SkillsListParams", ResponseSchemaRef: "#/definitions/SkillsListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"skills/extraRoots/set":                    {Method: "skills/extraRoots/set", Visibility: "public", ParamsType: "SkillsExtraRootsSetParams", ResponseType: "SkillsExtraRootsSetResponse", ParamsSchemaRef: "#/definitions/SkillsExtraRootsSetParams", ResponseSchemaRef: "#/definitions/SkillsExtraRootsSetResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"hooks/list":                               {Method: "hooks/list", Visibility: "public", ParamsType: "HooksListParams", ResponseType: "HooksListResponse", ParamsSchemaRef: "#/definitions/HooksListParams", ResponseSchemaRef: "#/definitions/HooksListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"marketplace/add":                          {Method: "marketplace/add", Visibility: "public", ParamsType: "MarketplaceAddParams", ResponseType: "MarketplaceAddResponse", ParamsSchemaRef: "#/definitions/MarketplaceAddParams", ResponseSchemaRef: "#/definitions/MarketplaceAddResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"marketplace/remove":                       {Method: "marketplace/remove", Visibility: "public", ParamsType: "MarketplaceRemoveParams", ResponseType: "MarketplaceRemoveResponse", ParamsSchemaRef: "#/definitions/MarketplaceRemoveParams", ResponseSchemaRef: "#/definitions/MarketplaceRemoveResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"marketplace/upgrade":                      {Method: "marketplace/upgrade", Visibility: "public", ParamsType: "MarketplaceUpgradeParams", ResponseType: "MarketplaceUpgradeResponse", ParamsSchemaRef: "#/definitions/MarketplaceUpgradeParams", ResponseSchemaRef: "#/definitions/MarketplaceUpgradeResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/list":                              {Method: "plugin/list", Visibility: "public", ParamsType: "PluginListParams", ResponseType: "PluginListResponse", ParamsSchemaRef: "#/definitions/PluginListParams", ResponseSchemaRef: "#/definitions/PluginListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/installed":                         {Method: "plugin/installed", Visibility: "public", ParamsType: "PluginInstalledParams", ResponseType: "PluginInstalledResponse", ParamsSchemaRef: "#/definitions/PluginInstalledParams", ResponseSchemaRef: "#/definitions/PluginInstalledResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/read":                              {Method: "plugin/read", Visibility: "public", ParamsType: "PluginReadParams", ResponseType: "PluginReadResponse", ParamsSchemaRef: "#/definitions/PluginReadParams", ResponseSchemaRef: "#/definitions/PluginReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/skill/read":                        {Method: "plugin/skill/read", Visibility: "public", ParamsType: "PluginSkillReadParams", ResponseType: "PluginSkillReadResponse", ParamsSchemaRef: "#/definitions/PluginSkillReadParams", ResponseSchemaRef: "#/definitions/PluginSkillReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/share/save":                        {Method: "plugin/share/save", Visibility: "public", ParamsType: "PluginShareSaveParams", ResponseType: "PluginShareSaveResponse", ParamsSchemaRef: "#/definitions/PluginShareSaveParams", ResponseSchemaRef: "#/definitions/PluginShareSaveResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/share/updateTargets":               {Method: "plugin/share/updateTargets", Visibility: "public", ParamsType: "PluginShareUpdateTargetsParams", ResponseType: "PluginShareUpdateTargetsResponse", ParamsSchemaRef: "#/definitions/PluginShareUpdateTargetsParams", ResponseSchemaRef: "#/definitions/PluginShareUpdateTargetsResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/share/list":                        {Method: "plugin/share/list", Visibility: "public", ParamsType: "PluginShareListParams", ResponseType: "PluginShareListResponse", ParamsSchemaRef: "#/definitions/PluginShareListParams", ResponseSchemaRef: "#/definitions/PluginShareListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/share/checkout":                    {Method: "plugin/share/checkout", Visibility: "public", ParamsType: "PluginShareCheckoutParams", ResponseType: "PluginShareCheckoutResponse", ParamsSchemaRef: "#/definitions/PluginShareCheckoutParams", ResponseSchemaRef: "#/definitions/PluginShareCheckoutResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/share/delete":                      {Method: "plugin/share/delete", Visibility: "public", ParamsType: "PluginShareDeleteParams", ResponseType: "PluginShareDeleteResponse", ParamsSchemaRef: "#/definitions/PluginShareDeleteParams", ResponseSchemaRef: "#/definitions/PluginShareDeleteResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"app/list":                                 {Method: "app/list", Visibility: "public", ParamsType: "AppsListParams", ResponseType: "AppsListResponse", ParamsSchemaRef: "#/definitions/AppsListParams", ResponseSchemaRef: "#/definitions/AppsListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/readFile":                              {Method: "fs/readFile", Visibility: "public", ParamsType: "FsReadFileParams", ResponseType: "FsReadFileResponse", ParamsSchemaRef: "#/definitions/FsReadFileParams", ResponseSchemaRef: "#/definitions/FsReadFileResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/writeFile":                             {Method: "fs/writeFile", Visibility: "public", ParamsType: "FsWriteFileParams", ResponseType: "FsWriteFileResponse", ParamsSchemaRef: "#/definitions/FsWriteFileParams", ResponseSchemaRef: "#/definitions/FsWriteFileResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/createDirectory":                       {Method: "fs/createDirectory", Visibility: "public", ParamsType: "FsCreateDirectoryParams", ResponseType: "FsCreateDirectoryResponse", ParamsSchemaRef: "#/definitions/FsCreateDirectoryParams", ResponseSchemaRef: "#/definitions/FsCreateDirectoryResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/getMetadata":                           {Method: "fs/getMetadata", Visibility: "public", ParamsType: "FsGetMetadataParams", ResponseType: "FsGetMetadataResponse", ParamsSchemaRef: "#/definitions/FsGetMetadataParams", ResponseSchemaRef: "#/definitions/FsGetMetadataResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/readDirectory":                         {Method: "fs/readDirectory", Visibility: "public", ParamsType: "FsReadDirectoryParams", ResponseType: "FsReadDirectoryResponse", ParamsSchemaRef: "#/definitions/FsReadDirectoryParams", ResponseSchemaRef: "#/definitions/FsReadDirectoryResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/remove":                                {Method: "fs/remove", Visibility: "public", ParamsType: "FsRemoveParams", ResponseType: "FsRemoveResponse", ParamsSchemaRef: "#/definitions/FsRemoveParams", ResponseSchemaRef: "#/definitions/FsRemoveResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/copy":                                  {Method: "fs/copy", Visibility: "public", ParamsType: "FsCopyParams", ResponseType: "FsCopyResponse", ParamsSchemaRef: "#/definitions/FsCopyParams", ResponseSchemaRef: "#/definitions/FsCopyResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/watch":                                 {Method: "fs/watch", Visibility: "public", ParamsType: "FsWatchParams", ResponseType: "FsWatchResponse", ParamsSchemaRef: "#/definitions/FsWatchParams", ResponseSchemaRef: "#/definitions/FsWatchResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fs/unwatch":                               {Method: "fs/unwatch", Visibility: "public", ParamsType: "FsUnwatchParams", ResponseType: "FsUnwatchResponse", ParamsSchemaRef: "#/definitions/FsUnwatchParams", ResponseSchemaRef: "#/definitions/FsUnwatchResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"skills/config/write":                      {Method: "skills/config/write", Visibility: "public", ParamsType: "SkillsConfigWriteParams", ResponseType: "SkillsConfigWriteResponse", ParamsSchemaRef: "#/definitions/SkillsConfigWriteParams", ResponseSchemaRef: "#/definitions/SkillsConfigWriteResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/install":                           {Method: "plugin/install", Visibility: "public", ParamsType: "PluginInstallParams", ResponseType: "PluginInstallResponse", ParamsSchemaRef: "#/definitions/PluginInstallParams", ResponseSchemaRef: "#/definitions/PluginInstallResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"plugin/uninstall":                         {Method: "plugin/uninstall", Visibility: "public", ParamsType: "PluginUninstallParams", ResponseType: "PluginUninstallResponse", ParamsSchemaRef: "#/definitions/PluginUninstallParams", ResponseSchemaRef: "#/definitions/PluginUninstallResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"turn/start":                               {Method: "turn/start", Visibility: "public", ParamsType: "TurnStartParams", ResponseType: "TurnStartResponse", ParamsSchemaRef: "#/definitions/TurnStartParams", ResponseSchemaRef: "#/definitions/TurnStartResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", BoundedModelContextFields: []BoundedModelContextFieldMetadata{{Method: "turn/start", FieldPath: "additional_context.*.value", LimitProfile: "additionalContextValueBytes"}}, ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "TurnStartParams", FieldPath: "responsesapi_client_metadata", Reason: "turn/start.responsesapiClientMetadata", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnStartParams", FieldPath: "additional_context", Reason: "turn/start.additionalContext", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnStartParams", FieldPath: "environments", Reason: "turn/start.environments", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnStartParams", FieldPath: "runtime_workspace_roots", Reason: "turn/start.runtimeWorkspaceRoots", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnStartParams", FieldPath: "approval_policy", Reason: "nested", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnStartParams", FieldPath: "permissions", Reason: "turn/start.permissions", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnStartParams", FieldPath: "collaboration_mode", Reason: "turn/start.collaborationMode", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnStartParams", FieldPath: "multi_agent_mode", Reason: "turn/start.multiAgentMode", InspectParams: true, DiscriminatorJSON: ""}}},
	"turn/steer":                               {Method: "turn/steer", Visibility: "public", ParamsType: "TurnSteerParams", ResponseType: "TurnSteerResponse", ParamsSchemaRef: "#/definitions/TurnSteerParams", ResponseSchemaRef: "#/definitions/TurnSteerResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", BoundedModelContextFields: []BoundedModelContextFieldMetadata{{Method: "turn/steer", FieldPath: "additional_context.*.value", LimitProfile: "additionalContextValueBytes"}}, ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "TurnSteerParams", FieldPath: "responsesapi_client_metadata", Reason: "turn/steer.responsesapiClientMetadata", InspectParams: true, DiscriminatorJSON: ""}, {ContainingType: "TurnSteerParams", FieldPath: "additional_context", Reason: "turn/steer.additionalContext", InspectParams: true, DiscriminatorJSON: ""}}},
	"turn/interrupt":                           {Method: "turn/interrupt", Visibility: "public", ParamsType: "TurnInterruptParams", ResponseType: "TurnInterruptResponse", ParamsSchemaRef: "#/definitions/TurnInterruptParams", ResponseSchemaRef: "#/definitions/TurnInterruptResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"thread/realtime/start":                    {Method: "thread/realtime/start", Visibility: "public", ParamsType: "ThreadRealtimeStartParams", ResponseType: "ThreadRealtimeStartResponse", ParamsSchemaRef: "#/definitions/ThreadRealtimeStartParams", ResponseSchemaRef: "#/definitions/ThreadRealtimeStartResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/realtime/appendAudio":              {Method: "thread/realtime/appendAudio", Visibility: "public", ParamsType: "ThreadRealtimeAppendAudioParams", ResponseType: "ThreadRealtimeAppendAudioResponse", ParamsSchemaRef: "#/definitions/ThreadRealtimeAppendAudioParams", ResponseSchemaRef: "#/definitions/ThreadRealtimeAppendAudioResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/realtime/appendText":               {Method: "thread/realtime/appendText", Visibility: "public", ParamsType: "ThreadRealtimeAppendTextParams", ResponseType: "ThreadRealtimeAppendTextResponse", ParamsSchemaRef: "#/definitions/ThreadRealtimeAppendTextParams", ResponseSchemaRef: "#/definitions/ThreadRealtimeAppendTextResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/realtime/appendSpeech":             {Method: "thread/realtime/appendSpeech", Visibility: "public", ParamsType: "ThreadRealtimeAppendSpeechParams", ResponseType: "ThreadRealtimeAppendSpeechResponse", ParamsSchemaRef: "#/definitions/ThreadRealtimeAppendSpeechParams", ResponseSchemaRef: "#/definitions/ThreadRealtimeAppendSpeechResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/realtime/stop":                     {Method: "thread/realtime/stop", Visibility: "public", ParamsType: "ThreadRealtimeStopParams", ResponseType: "ThreadRealtimeStopResponse", ParamsSchemaRef: "#/definitions/ThreadRealtimeStopParams", ResponseSchemaRef: "#/definitions/ThreadRealtimeStopResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"thread/realtime/listVoices":               {Method: "thread/realtime/listVoices", Visibility: "public", ParamsType: "ThreadRealtimeListVoicesParams", ResponseType: "ThreadRealtimeListVoicesResponse", ParamsSchemaRef: "#/definitions/ThreadRealtimeListVoicesParams", ResponseSchemaRef: "#/definitions/ThreadRealtimeListVoicesResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"review/start":                             {Method: "review/start", Visibility: "public", ParamsType: "ReviewStartParams", ResponseType: "ReviewStartResponse", ParamsSchemaRef: "#/definitions/ReviewStartParams", ResponseSchemaRef: "#/definitions/ReviewStartResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"model/list":                               {Method: "model/list", Visibility: "public", ParamsType: "ModelListParams", ResponseType: "ModelListResponse", ParamsSchemaRef: "#/definitions/ModelListParams", ResponseSchemaRef: "#/definitions/ModelListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"modelProvider/capabilities/read":          {Method: "modelProvider/capabilities/read", Visibility: "public", ParamsType: "ModelProviderCapabilitiesReadParams", ResponseType: "ModelProviderCapabilitiesReadResponse", ParamsSchemaRef: "#/definitions/ModelProviderCapabilitiesReadParams", ResponseSchemaRef: "#/definitions/ModelProviderCapabilitiesReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"experimentalFeature/list":                 {Method: "experimentalFeature/list", Visibility: "public", ParamsType: "ExperimentalFeatureListParams", ResponseType: "ExperimentalFeatureListResponse", ParamsSchemaRef: "#/definitions/ExperimentalFeatureListParams", ResponseSchemaRef: "#/definitions/ExperimentalFeatureListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"permissionProfile/list":                   {Method: "permissionProfile/list", Visibility: "public", ParamsType: "PermissionProfileListParams", ResponseType: "PermissionProfileListResponse", ParamsSchemaRef: "#/definitions/PermissionProfileListParams", ResponseSchemaRef: "#/definitions/PermissionProfileListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"experimentalFeature/enablement/set":       {Method: "experimentalFeature/enablement/set", Visibility: "public", ParamsType: "ExperimentalFeatureEnablementSetParams", ResponseType: "ExperimentalFeatureEnablementSetResponse", ParamsSchemaRef: "#/definitions/ExperimentalFeatureEnablementSetParams", ResponseSchemaRef: "#/definitions/ExperimentalFeatureEnablementSetResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"remoteControl/enable":                     {Method: "remoteControl/enable", Visibility: "public", ParamsType: "NullableRemoteControlEnableParams", ResponseType: "RemoteControlEnableResponse", ParamsSchemaRef: "#/definitions/NullableRemoteControlEnableParams", ResponseSchemaRef: "#/definitions/RemoteControlEnableResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"remoteControl/disable":                    {Method: "remoteControl/disable", Visibility: "public", ParamsType: "NullableRemoteControlDisableParams", ResponseType: "RemoteControlDisableResponse", ParamsSchemaRef: "#/definitions/NullableRemoteControlDisableParams", ResponseSchemaRef: "#/definitions/RemoteControlDisableResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"remoteControl/status/read":                {Method: "remoteControl/status/read", Visibility: "public", ParamsType: "Option<()>", ResponseType: "RemoteControlStatusReadResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/RemoteControlStatusReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"remoteControl/pairing/start":              {Method: "remoteControl/pairing/start", Visibility: "public", ParamsType: "RemoteControlPairingStartParams", ResponseType: "RemoteControlPairingStartResponse", ParamsSchemaRef: "#/definitions/RemoteControlPairingStartParams", ResponseSchemaRef: "#/definitions/RemoteControlPairingStartResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"remoteControl/pairing/status":             {Method: "remoteControl/pairing/status", Visibility: "public", ParamsType: "RemoteControlPairingStatusParams", ResponseType: "RemoteControlPairingStatusResponse", ParamsSchemaRef: "#/definitions/RemoteControlPairingStatusParams", ResponseSchemaRef: "#/definitions/RemoteControlPairingStatusResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"remoteControl/client/list":                {Method: "remoteControl/client/list", Visibility: "public", ParamsType: "RemoteControlClientsListParams", ResponseType: "RemoteControlClientsListResponse", ParamsSchemaRef: "#/definitions/RemoteControlClientsListParams", ResponseSchemaRef: "#/definitions/RemoteControlClientsListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"remoteControl/client/revoke":              {Method: "remoteControl/client/revoke", Visibility: "public", ParamsType: "RemoteControlClientsRevokeParams", ResponseType: "RemoteControlClientsRevokeResponse", ParamsSchemaRef: "#/definitions/RemoteControlClientsRevokeParams", ResponseSchemaRef: "#/definitions/RemoteControlClientsRevokeResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"collaborationMode/list":                   {Method: "collaborationMode/list", Visibility: "public", ParamsType: "CollaborationModeListParams", ResponseType: "CollaborationModeListResponse", ParamsSchemaRef: "#/definitions/CollaborationModeListParams", ResponseSchemaRef: "#/definitions/CollaborationModeListResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"environment/add":                          {Method: "environment/add", Visibility: "public", ParamsType: "EnvironmentAddParams", ResponseType: "EnvironmentAddResponse", ParamsSchemaRef: "#/definitions/EnvironmentAddParams", ResponseSchemaRef: "#/definitions/EnvironmentAddResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"environment/info":                         {Method: "environment/info", Visibility: "public", ParamsType: "EnvironmentInfoParams", ResponseType: "EnvironmentInfoResponse", ParamsSchemaRef: "#/definitions/EnvironmentInfoParams", ResponseSchemaRef: "#/definitions/EnvironmentInfoResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"mcpServer/oauth/login":                    {Method: "mcpServer/oauth/login", Visibility: "public", ParamsType: "McpServerOauthLoginParams", ResponseType: "McpServerOauthLoginResponse", ParamsSchemaRef: "#/definitions/McpServerOauthLoginParams", ResponseSchemaRef: "#/definitions/McpServerOauthLoginResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"config/mcpServer/reload":                  {Method: "config/mcpServer/reload", Visibility: "public", ParamsType: "Option<()>", ResponseType: "McpServerRefreshResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/McpServerRefreshResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"mcpServerStatus/list":                     {Method: "mcpServerStatus/list", Visibility: "public", ParamsType: "ListMcpServerStatusParams", ResponseType: "ListMcpServerStatusResponse", ParamsSchemaRef: "#/definitions/ListMcpServerStatusParams", ResponseSchemaRef: "#/definitions/ListMcpServerStatusResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"mcpServer/resource/read":                  {Method: "mcpServer/resource/read", Visibility: "public", ParamsType: "McpResourceReadParams", ResponseType: "McpResourceReadResponse", ParamsSchemaRef: "#/definitions/McpResourceReadParams", ResponseSchemaRef: "#/definitions/McpResourceReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"mcpServer/tool/call":                      {Method: "mcpServer/tool/call", Visibility: "public", ParamsType: "McpServerToolCallParams", ResponseType: "McpServerToolCallResponse", ParamsSchemaRef: "#/definitions/McpServerToolCallParams", ResponseSchemaRef: "#/definitions/McpServerToolCallResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"windowsSandbox/setupStart":                {Method: "windowsSandbox/setupStart", Visibility: "public", ParamsType: "WindowsSandboxSetupStartParams", ResponseType: "WindowsSandboxSetupStartResponse", ParamsSchemaRef: "#/definitions/WindowsSandboxSetupStartParams", ResponseSchemaRef: "#/definitions/WindowsSandboxSetupStartResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"windowsSandbox/readiness":                 {Method: "windowsSandbox/readiness", Visibility: "public", ParamsType: "Option<()>", ResponseType: "WindowsSandboxReadinessResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/WindowsSandboxReadinessResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"account/login/start":                      {Method: "account/login/start", Visibility: "public", ParamsType: "LoginAccountParams", ResponseType: "LoginAccountResponse", ParamsSchemaRef: "#/definitions/LoginAccountParams", ResponseSchemaRef: "#/definitions/LoginAccountResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "LoginAccountParams", FieldPath: "type", Reason: "account/login/start.chatgptAuthTokens", InspectParams: true, DiscriminatorJSON: "{\n              \"fieldPath\": \"type\",\n              \"wireValue\": \"chatgptAuthTokens\"\n            }"}}},
	"account/login/cancel":                     {Method: "account/login/cancel", Visibility: "public", ParamsType: "CancelLoginAccountParams", ResponseType: "CancelLoginAccountResponse", ParamsSchemaRef: "#/definitions/CancelLoginAccountParams", ResponseSchemaRef: "#/definitions/CancelLoginAccountResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"account/logout":                           {Method: "account/logout", Visibility: "public", ParamsType: "Option<()>", ResponseType: "LogoutAccountResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/LogoutAccountResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"account/rateLimits/read":                  {Method: "account/rateLimits/read", Visibility: "public", ParamsType: "Option<()>", ResponseType: "GetAccountRateLimitsResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/GetAccountRateLimitsResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"account/rateLimitResetCredit/consume":     {Method: "account/rateLimitResetCredit/consume", Visibility: "public", ParamsType: "ConsumeAccountRateLimitResetCreditParams", ResponseType: "ConsumeAccountRateLimitResetCreditResponse", ParamsSchemaRef: "#/definitions/ConsumeAccountRateLimitResetCreditParams", ResponseSchemaRef: "#/definitions/ConsumeAccountRateLimitResetCreditResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"account/usage/read":                       {Method: "account/usage/read", Visibility: "public", ParamsType: "Option<()>", ResponseType: "GetAccountTokenUsageResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/GetAccountTokenUsageResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"account/workspaceMessages/read":           {Method: "account/workspaceMessages/read", Visibility: "public", ParamsType: "Option<()>", ResponseType: "GetWorkspaceMessagesResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/GetWorkspaceMessagesResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"account/sendAddCreditsNudgeEmail":         {Method: "account/sendAddCreditsNudgeEmail", Visibility: "public", ParamsType: "SendAddCreditsNudgeEmailParams", ResponseType: "SendAddCreditsNudgeEmailResponse", ParamsSchemaRef: "#/definitions/SendAddCreditsNudgeEmailParams", ResponseSchemaRef: "#/definitions/SendAddCreditsNudgeEmailResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"feedback/upload":                          {Method: "feedback/upload", Visibility: "public", ParamsType: "FeedbackUploadParams", ResponseType: "FeedbackUploadResponse", ParamsSchemaRef: "#/definitions/FeedbackUploadParams", ResponseSchemaRef: "#/definitions/FeedbackUploadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"command/exec":                             {Method: "command/exec", Visibility: "public", ParamsType: "CommandExecParams", ResponseType: "CommandExecResponse", ParamsSchemaRef: "#/definitions/CommandExecParams", ResponseSchemaRef: "#/definitions/CommandExecResponse", SchemaExcludedReason: "", InspectParams: true, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "CommandExecParams", FieldPath: "permission_profile", Reason: "command/exec.permissionProfile", InspectParams: true, DiscriminatorJSON: ""}}},
	"command/exec/write":                       {Method: "command/exec/write", Visibility: "public", ParamsType: "CommandExecWriteParams", ResponseType: "CommandExecWriteResponse", ParamsSchemaRef: "#/definitions/CommandExecWriteParams", ResponseSchemaRef: "#/definitions/CommandExecWriteResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"command/exec/terminate":                   {Method: "command/exec/terminate", Visibility: "public", ParamsType: "CommandExecTerminateParams", ResponseType: "CommandExecTerminateResponse", ParamsSchemaRef: "#/definitions/CommandExecTerminateParams", ResponseSchemaRef: "#/definitions/CommandExecTerminateResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"command/exec/resize":                      {Method: "command/exec/resize", Visibility: "public", ParamsType: "CommandExecResizeParams", ResponseType: "CommandExecResizeResponse", ParamsSchemaRef: "#/definitions/CommandExecResizeParams", ResponseSchemaRef: "#/definitions/CommandExecResizeResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"process/spawn":                            {Method: "process/spawn", Visibility: "public", ParamsType: "ProcessSpawnParams", ResponseType: "ProcessSpawnResponse", ParamsSchemaRef: "#/definitions/ProcessSpawnParams", ResponseSchemaRef: "#/definitions/ProcessSpawnResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"process/writeStdin":                       {Method: "process/writeStdin", Visibility: "public", ParamsType: "ProcessWriteStdinParams", ResponseType: "ProcessWriteStdinResponse", ParamsSchemaRef: "#/definitions/ProcessWriteStdinParams", ResponseSchemaRef: "#/definitions/ProcessWriteStdinResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"process/kill":                             {Method: "process/kill", Visibility: "public", ParamsType: "ProcessKillParams", ResponseType: "ProcessKillResponse", ParamsSchemaRef: "#/definitions/ProcessKillParams", ResponseSchemaRef: "#/definitions/ProcessKillResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"process/resizePty":                        {Method: "process/resizePty", Visibility: "public", ParamsType: "ProcessResizePtyParams", ResponseType: "ProcessResizePtyResponse", ParamsSchemaRef: "#/definitions/ProcessResizePtyParams", ResponseSchemaRef: "#/definitions/ProcessResizePtyResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"config/read":                              {Method: "config/read", Visibility: "public", ParamsType: "ConfigReadParams", ResponseType: "ConfigReadResponse", ParamsSchemaRef: "#/definitions/ConfigReadParams", ResponseSchemaRef: "#/definitions/ConfigReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "ConfigReadResponse", FieldPath: "config", Reason: "nested", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "Config", FieldPath: "config.approval_policy", Reason: "nested", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "Config", FieldPath: "config.approvals_reviewer", Reason: "config/read.approvalsReviewer", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "Config", FieldPath: "config.apps", Reason: "config/read.apps", InspectParams: false, DiscriminatorJSON: ""}}},
	"externalAgentConfig/detect":               {Method: "externalAgentConfig/detect", Visibility: "public", ParamsType: "ExternalAgentConfigDetectParams", ResponseType: "ExternalAgentConfigDetectResponse", ParamsSchemaRef: "#/definitions/ExternalAgentConfigDetectParams", ResponseSchemaRef: "#/definitions/ExternalAgentConfigDetectResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"externalAgentConfig/import":               {Method: "externalAgentConfig/import", Visibility: "public", ParamsType: "ExternalAgentConfigImportParams", ResponseType: "ExternalAgentConfigImportResponse", ParamsSchemaRef: "#/definitions/ExternalAgentConfigImportParams", ResponseSchemaRef: "#/definitions/ExternalAgentConfigImportResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"externalAgentConfig/import/readHistories": {Method: "externalAgentConfig/import/readHistories", Visibility: "public", ParamsType: "Option<()>", ResponseType: "ExternalAgentConfigImportHistoriesReadResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/ExternalAgentConfigImportHistoriesReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"config/value/write":                       {Method: "config/value/write", Visibility: "public", ParamsType: "ConfigValueWriteParams", ResponseType: "ConfigWriteResponse", ParamsSchemaRef: "#/definitions/ConfigValueWriteParams", ResponseSchemaRef: "#/definitions/ConfigWriteResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "manual response payload conversion", Experimental: false, Retry: "neverRetryAfterWrite"},
	"config/batchWrite":                        {Method: "config/batchWrite", Visibility: "public", ParamsType: "ConfigBatchWriteParams", ResponseType: "ConfigWriteResponse", ParamsSchemaRef: "#/definitions/ConfigBatchWriteParams", ResponseSchemaRef: "#/definitions/ConfigWriteResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "manual response payload conversion", Experimental: false, Retry: "neverRetryAfterWrite"},
	"configRequirements/read":                  {Method: "configRequirements/read", Visibility: "public", ParamsType: "Option<()>", ResponseType: "ConfigRequirementsReadResponse", ParamsSchemaRef: "", ResponseSchemaRef: "#/definitions/ConfigRequirementsReadResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite", ExperimentalFields: []ExperimentalFieldMetadata{{ContainingType: "ConfigRequirementsReadResponse", FieldPath: "requirements", Reason: "nested", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ConfigRequirements", FieldPath: "requirements.allowed_approval_policies", Reason: "nested", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ConfigRequirements", FieldPath: "requirements.allowed_approvals_reviewers", Reason: "configRequirements/read.allowedApprovalsReviewers", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ConfigRequirements", FieldPath: "requirements.hooks", Reason: "configRequirements/read.hooks", InspectParams: false, DiscriminatorJSON: ""}, {ContainingType: "ConfigRequirements", FieldPath: "requirements.network", Reason: "configRequirements/read.network", InspectParams: false, DiscriminatorJSON: ""}}},
	"account/read":                             {Method: "account/read", Visibility: "public", ParamsType: "GetAccountParams", ResponseType: "GetAccountResponse", ParamsSchemaRef: "#/definitions/GetAccountParams", ResponseSchemaRef: "#/definitions/GetAccountResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"getConversationSummary":                   {Method: "getConversationSummary", Visibility: "compatibilityOnly", ParamsType: "GetConversationSummaryParams", ResponseType: "GetConversationSummaryResponse", ParamsSchemaRef: "", ResponseSchemaRef: "", SchemaExcludedReason: "deprecated v1 compatibility request schemas are intentionally excluded from Go SDK schema inputs", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"gitDiffToRemote":                          {Method: "gitDiffToRemote", Visibility: "compatibilityOnly", ParamsType: "GitDiffToRemoteParams", ResponseType: "GitDiffToRemoteResponse", ParamsSchemaRef: "", ResponseSchemaRef: "", SchemaExcludedReason: "deprecated v1 compatibility request schemas are intentionally excluded from Go SDK schema inputs", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"getAuthStatus":                            {Method: "getAuthStatus", Visibility: "compatibilityOnly", ParamsType: "GetAuthStatusParams", ResponseType: "GetAuthStatusResponse", ParamsSchemaRef: "", ResponseSchemaRef: "", SchemaExcludedReason: "deprecated v1 compatibility request schemas are intentionally excluded from Go SDK schema inputs", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fuzzyFileSearch":                          {Method: "fuzzyFileSearch", Visibility: "public", ParamsType: "FuzzyFileSearchParams", ResponseType: "FuzzyFileSearchResponse", ParamsSchemaRef: "#/definitions/FuzzyFileSearchParams", ResponseSchemaRef: "#/definitions/FuzzyFileSearchResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: false, Retry: "neverRetryAfterWrite"},
	"fuzzyFileSearch/sessionStart":             {Method: "fuzzyFileSearch/sessionStart", Visibility: "public", ParamsType: "FuzzyFileSearchSessionStartParams", ResponseType: "FuzzyFileSearchSessionStartResponse", ParamsSchemaRef: "#/definitions/FuzzyFileSearchSessionStartParams", ResponseSchemaRef: "#/definitions/FuzzyFileSearchSessionStartResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"fuzzyFileSearch/sessionUpdate":            {Method: "fuzzyFileSearch/sessionUpdate", Visibility: "public", ParamsType: "FuzzyFileSearchSessionUpdateParams", ResponseType: "FuzzyFileSearchSessionUpdateResponse", ParamsSchemaRef: "#/definitions/FuzzyFileSearchSessionUpdateParams", ResponseSchemaRef: "#/definitions/FuzzyFileSearchSessionUpdateResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
	"fuzzyFileSearch/sessionStop":              {Method: "fuzzyFileSearch/sessionStop", Visibility: "public", ParamsType: "FuzzyFileSearchSessionStopParams", ResponseType: "FuzzyFileSearchSessionStopResponse", ParamsSchemaRef: "#/definitions/FuzzyFileSearchSessionStopParams", ResponseSchemaRef: "#/definitions/FuzzyFileSearchSessionStopResponse", SchemaExcludedReason: "", InspectParams: false, ManualPayloadConversion: "", Experimental: true, Retry: "neverRetryAfterWrite"},
}
