package protocol

type ServerRequestMetadata struct {
	Method                  string
	Visibility              string
	ParamsType              string
	ResponseType            string
	ParamsSchemaRef         string
	ResponseSchemaRef       string
	SchemaExcludedReason    string
	ManualPayloadConversion string
	Capability              string
	HandlerOwner            string
	DecodeFunction          string
	Experimental            bool
}

var ServerRequestMetadataByMethod = map[string]ServerRequestMetadata{
	"item/commandExecution/requestApproval": {Method: "item/commandExecution/requestApproval", Visibility: "sdk-public", ParamsType: "CommandExecutionRequestApprovalParams", ResponseType: "CommandExecutionRequestApprovalResponse", ParamsSchemaRef: "#/definitions/CommandExecutionRequestApprovalParams", ResponseSchemaRef: "#/definitions/CommandExecutionRequestApprovalResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "command-execution-approval", HandlerOwner: "ServerHandlers.Approvals", DecodeFunction: "decodeItemCommandExecutionRequestApprovalServerRequest", Experimental: false},
	"item/fileChange/requestApproval":       {Method: "item/fileChange/requestApproval", Visibility: "sdk-public", ParamsType: "FileChangeRequestApprovalParams", ResponseType: "FileChangeRequestApprovalResponse", ParamsSchemaRef: "#/definitions/FileChangeRequestApprovalParams", ResponseSchemaRef: "#/definitions/FileChangeRequestApprovalResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "file-change-approval", HandlerOwner: "ServerHandlers.Approvals", DecodeFunction: "decodeItemFileChangeRequestApprovalServerRequest", Experimental: false},
	"item/tool/requestUserInput":            {Method: "item/tool/requestUserInput", Visibility: "sdk-public", ParamsType: "ToolRequestUserInputParams", ResponseType: "ToolRequestUserInputResponse", ParamsSchemaRef: "#/definitions/ToolRequestUserInputParams", ResponseSchemaRef: "#/definitions/ToolRequestUserInputResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "tool-user-input", HandlerOwner: "ServerHandlers.UserInput", DecodeFunction: "decodeItemToolRequestUserInputServerRequest", Experimental: false},
	"mcpServer/elicitation/request":         {Method: "mcpServer/elicitation/request", Visibility: "sdk-public", ParamsType: "McpServerElicitationRequestParams", ResponseType: "McpServerElicitationRequestResponse", ParamsSchemaRef: "#/definitions/McpServerElicitationRequestParams", ResponseSchemaRef: "#/definitions/McpServerElicitationRequestResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "mcp-elicitation", HandlerOwner: "ServerHandlers.MCPElicitation", DecodeFunction: "decodeMcpServerElicitationRequestServerRequest", Experimental: false},
	"item/permissions/requestApproval":      {Method: "item/permissions/requestApproval", Visibility: "sdk-public", ParamsType: "PermissionsRequestApprovalParams", ResponseType: "PermissionsRequestApprovalResponse", ParamsSchemaRef: "#/definitions/PermissionsRequestApprovalParams", ResponseSchemaRef: "#/definitions/PermissionsRequestApprovalResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "permission-approval", HandlerOwner: "ServerHandlers.Permissions", DecodeFunction: "decodeItemPermissionsRequestApprovalServerRequest", Experimental: false},
	"item/tool/call":                        {Method: "item/tool/call", Visibility: "sdk-public", ParamsType: "DynamicToolCallParams", ResponseType: "DynamicToolCallResponse", ParamsSchemaRef: "#/definitions/DynamicToolCallParams", ResponseSchemaRef: "#/definitions/DynamicToolCallResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "dynamic-tool-call", HandlerOwner: "ServerHandlers.DynamicTools", DecodeFunction: "decodeItemToolCallServerRequest", Experimental: false},
	"account/chatgptAuthTokens/refresh":     {Method: "account/chatgptAuthTokens/refresh", Visibility: "sdk-public", ParamsType: "ChatgptAuthTokensRefreshParams", ResponseType: "ChatgptAuthTokensRefreshResponse", ParamsSchemaRef: "#/definitions/ChatgptAuthTokensRefreshParams", ResponseSchemaRef: "#/definitions/ChatgptAuthTokensRefreshResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "chatgpt-token-refresh", HandlerOwner: "ServerHandlers.ChatGPTTokenRefresh", DecodeFunction: "decodeAccountChatgptAuthTokensRefreshServerRequest", Experimental: false},
	"attestation/generate":                  {Method: "attestation/generate", Visibility: "sdk-public", ParamsType: "AttestationGenerateParams", ResponseType: "AttestationGenerateResponse", ParamsSchemaRef: "#/definitions/AttestationGenerateParams", ResponseSchemaRef: "#/definitions/AttestationGenerateResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "attestation-generate", HandlerOwner: "ServerHandlers.Attestation", DecodeFunction: "decodeAttestationGenerateServerRequest", Experimental: false},
	"currentTime/read":                      {Method: "currentTime/read", Visibility: "experimental-public", ParamsType: "CurrentTimeReadParams", ResponseType: "CurrentTimeReadResponse", ParamsSchemaRef: "#/definitions/CurrentTimeReadParams", ResponseSchemaRef: "#/definitions/CurrentTimeReadResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "current-time-read", HandlerOwner: "ServerHandlers.CurrentTime", DecodeFunction: "decodeCurrentTimeReadServerRequest", Experimental: true},
	"applyPatchApproval":                    {Method: "applyPatchApproval", Visibility: "compatibility-only", ParamsType: "ApplyPatchApprovalParams", ResponseType: "ApplyPatchApprovalResponse", ParamsSchemaRef: "#/definitions/ApplyPatchApprovalParams", ResponseSchemaRef: "#/definitions/ApplyPatchApprovalResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "legacy-apply-patch-approval", HandlerOwner: "internal compatibility dispatch/decode only; no public handler field", DecodeFunction: "decodeApplyPatchApprovalServerRequest", Experimental: false},
	"execCommandApproval":                   {Method: "execCommandApproval", Visibility: "compatibility-only", ParamsType: "ExecCommandApprovalParams", ResponseType: "ExecCommandApprovalResponse", ParamsSchemaRef: "#/definitions/ExecCommandApprovalParams", ResponseSchemaRef: "#/definitions/ExecCommandApprovalResponse", SchemaExcludedReason: "", ManualPayloadConversion: "", Capability: "legacy-exec-command-approval", HandlerOwner: "internal compatibility dispatch/decode only; no public handler field", DecodeFunction: "decodeExecCommandApprovalServerRequest", Experimental: false},
}
