use super::serde_shape_fields::*;
use super::*;

pub(super) fn go_sdk_serde_shapes() -> Vec<SerdeShapeEntry> {
    vec![
        SerdeShapeEntry {
            rust_type: "AppScreenshot".to_string(),
            schema_ref: Some("#/definitions/AppScreenshot".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                serde_field(
                    "file_id",
                    "fileId",
                    &["file_id"],
                    SerdeFieldShape {
                        presence: SerdePresence::OptionalNullable,
                        default: None,
                        skip_serializing_if: None,
                        flattened: false,
                        custom_serialize: None,
                        custom_deserialize: None,
                    },
                ),
                serde_field(
                    "user_prompt",
                    "userPrompt",
                    &["user_prompt"],
                    SerdeFieldShape {
                        presence: SerdePresence::Required,
                        default: None,
                        skip_serializing_if: None,
                        flattened: false,
                        custom_serialize: None,
                        custom_deserialize: None,
                    },
                ),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "FileSystemSpecialPath".to_string(),
            schema_ref: Some("#/definitions/FileSystemSpecialPath".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: Vec::new(),
            variant_aliases: vec![SerdeVariantAliasEntry {
                rust_variant: "ProjectRoots",
                canonical_wire_value: "project_roots",
                aliases: vec!["current_working_directory"],
            }],
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "CollaborationModeMask".to_string(),
            schema_ref: Some("#/definitions/CollaborationModeMask".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![serde_field(
                "reasoning_effort",
                "reasoning_effort",
                &[],
                SerdeFieldShape {
                    presence: SerdePresence::DoubleOption,
                    default: None,
                    skip_serializing_if: None,
                    flattened: false,
                    custom_serialize: None,
                    custom_deserialize: None,
                },
            )],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "AnalyticsConfig".to_string(),
            schema_ref: Some("#/definitions/AnalyticsConfig".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![serde_field(
                "additional",
                "*",
                &[],
                SerdeFieldShape {
                    presence: SerdePresence::OptionalNonNull,
                    default: Some(SerdeDefault {
                        provider: SerdeDefaultProvider::SerdeDefault,
                        wire_value_json: "{}",
                    }),
                    skip_serializing_if: None,
                    flattened: true,
                    custom_serialize: None,
                    custom_deserialize: None,
                },
            )],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ThreadStartParams".to_string(),
            schema_ref: Some("#/definitions/ThreadStartParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                default_skip_false_field(
                    "allow_provider_model_fallback",
                    "allowProviderModelFallback",
                ),
                double_option_field("service_tier", "serviceTier"),
                serde_field(
                    "dynamic_tools",
                    "dynamicTools",
                    &[],
                    SerdeFieldShape {
                        presence: SerdePresence::OptionalNullable,
                        default: Some(SerdeDefault {
                            provider: SerdeDefaultProvider::SerdeDefault,
                            wire_value_json: "null",
                        }),
                        skip_serializing_if: None,
                        flattened: false,
                        custom_serialize: None,
                        custom_deserialize: Some(
                            "codex_protocol::dynamic_tools::deserialize_dynamic_tool_specs",
                        ),
                    },
                ),
                default_skip_false_field("experimental_raw_events", "experimentalRawEvents"),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ThreadStartResponse".to_string(),
            schema_ref: Some("#/definitions/ThreadStartResponse".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: thread_response_serde_fields(),
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ThreadResumeParams".to_string(),
            schema_ref: Some("#/definitions/ThreadResumeParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                double_option_field("service_tier", "serviceTier"),
                default_skip_false_field("exclude_turns", "excludeTurns"),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ThreadResumeResponse".to_string(),
            schema_ref: Some("#/definitions/ThreadResumeResponse".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: {
                let mut fields = thread_response_serde_fields();
                fields.push(default_field(
                    "initial_turns_page",
                    "initialTurnsPage",
                    SerdePresence::OptionalNullable,
                    "null",
                ));
                fields
            },
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ThreadForkParams".to_string(),
            schema_ref: Some("#/definitions/ThreadForkParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                double_option_field("service_tier", "serviceTier"),
                default_skip_false_field("ephemeral", "ephemeral"),
                default_skip_false_field("exclude_turns", "excludeTurns"),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ThreadForkResponse".to_string(),
            schema_ref: Some("#/definitions/ThreadForkResponse".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: thread_response_serde_fields(),
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "CommandExecParams".to_string(),
            schema_ref: Some("#/definitions/CommandExecParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                default_skip_false_field("tty", "tty"),
                default_skip_false_field("stream_stdin", "streamStdin"),
                default_skip_false_field("stream_stdout_stderr", "streamStdoutStderr"),
                default_skip_false_field("disable_output_cap", "disableOutputCap"),
                default_skip_false_field("disable_timeout", "disableTimeout"),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "LoginAccountParams".to_string(),
            schema_ref: Some("#/definitions/LoginAccountParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![default_skip_false_field(
                "codex_streamlined_login",
                "codexStreamlinedLogin",
            )],
            variant_aliases: vec![SerdeVariantAliasEntry {
                rust_variant: "ChatgptAuthTokens",
                canonical_wire_value: "chatgptAuthTokens",
                aliases: Vec::new(),
            }],
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "Config".to_string(),
            schema_ref: Some("#/definitions/Config".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                default_field("apps", "apps", SerdePresence::OptionalNullable, "null"),
                serde_field(
                    "additional",
                    "*",
                    &[],
                    SerdeFieldShape {
                        presence: SerdePresence::OptionalNonNull,
                        default: Some(SerdeDefault {
                            provider: SerdeDefaultProvider::SerdeDefault,
                            wire_value_json: "{}",
                        }),
                        skip_serializing_if: None,
                        flattened: true,
                        custom_serialize: None,
                        custom_deserialize: None,
                    },
                ),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ConfigReadParams".to_string(),
            schema_ref: Some("#/definitions/ConfigReadParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![default_skip_false_field("include_layers", "includeLayers")],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ConfigReadResponse".to_string(),
            schema_ref: Some("#/definitions/ConfigReadResponse".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![SerdeFieldEntry {
                rust_field: "layers",
                wire_name: "layers",
                aliases: Vec::new(),
                shape: SerdeFieldShape {
                    presence: SerdePresence::OptionalNullable,
                    default: None,
                    skip_serializing_if: Some("Option::is_none"),
                    flattened: false,
                    custom_serialize: None,
                    custom_deserialize: None,
                },
            }],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ConfigLayer".to_string(),
            schema_ref: Some("#/definitions/ConfigLayer".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![optional_skip_none_field(
                "disabled_reason",
                "disabledReason",
            )],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ConfigRequirements".to_string(),
            schema_ref: Some("#/definitions/ConfigRequirements".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: Vec::new(),
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: Some("reviewed manifest-required type with no field-level serde metadata"),
        },
        SerdeShapeEntry {
            rust_type: "ConfigRequirementsReadResponse".to_string(),
            schema_ref: Some("#/definitions/ConfigRequirementsReadResponse".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: Vec::new(),
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: Some("reviewed manifest-required type with no field-level serde metadata"),
        },
        SerdeShapeEntry {
            rust_type: "ConfigValueWriteParams".to_string(),
            schema_ref: Some("#/definitions/ConfigValueWriteParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: Vec::new(),
            variant_aliases: Vec::new(),
            manual_payload_conversion: Some("manual response payload conversion"),
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ConfigBatchWriteParams".to_string(),
            schema_ref: Some("#/definitions/ConfigBatchWriteParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![default_skip_false_field(
                "reload_user_config",
                "reloadUserConfig",
            )],
            variant_aliases: Vec::new(),
            manual_payload_conversion: Some("manual response payload conversion"),
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ProcessSpawnParams".to_string(),
            schema_ref: Some("#/definitions/ProcessSpawnParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                default_skip_false_field("tty", "tty"),
                default_skip_false_field("stream_stdin", "streamStdin"),
                default_skip_false_field("stream_stdout_stderr", "streamStdoutStderr"),
                double_option_field("output_bytes_cap", "outputBytesCap"),
                double_option_field("timeout_ms", "timeoutMs"),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "RemoteControlPairingStartParams".to_string(),
            schema_ref: Some("#/definitions/RemoteControlPairingStartParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![default_skip_false_field("manual_code", "manualCode")],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "RemoteControlPairingStartResponse".to_string(),
            schema_ref: Some("#/definitions/RemoteControlPairingStartResponse".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![serde_field(
                "manual_pairing_code",
                "manualPairingCode",
                &[],
                SerdeFieldShape {
                    presence: SerdePresence::OptionalNullable,
                    default: None,
                    skip_serializing_if: None,
                    flattened: false,
                    custom_serialize: None,
                    custom_deserialize: None,
                },
            )],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "ReviewStartResponse".to_string(),
            schema_ref: Some("#/definitions/ReviewStartResponse".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![serde_field(
                "review_thread_id",
                "reviewThreadId",
                &[],
                SerdeFieldShape {
                    presence: SerdePresence::Required,
                    default: None,
                    skip_serializing_if: None,
                    flattened: false,
                    custom_serialize: None,
                    custom_deserialize: None,
                },
            )],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
        SerdeShapeEntry {
            rust_type: "CommandExecutionRequestApprovalParams".to_string(),
            schema_ref: Some("#/definitions/CommandExecutionRequestApprovalParams".to_string()),
            metadata_status: SerdeMetadataStatus::ManifestRequired,
            schema_sufficient_proof: None,
            fields: vec![
                default_skip_none_field("command", "command"),
                default_skip_none_field("cwd", "cwd"),
                default_skip_none_field("command_actions", "commandActions"),
                default_skip_none_field("additional_permissions", "additionalPermissions"),
                default_skip_none_field("available_decisions", "availableDecisions"),
            ],
            variant_aliases: Vec::new(),
            manual_payload_conversion: None,
            review_note: None,
        },
    ]
}
